"""SQL helper functions backing the RLS policy set (Phase 4 — B1).

These are the app-managed equivalents of the Supabase `auth.uid()` /
`public.is_active_wingperson()` helpers the original RLS policies leaned on. They
are exposed two ways so the Migration stage can pick whichever fits the existing
machinery:

  * `RLS_FUNCTION_REGISTRY` — `alembic_utils.PGFunction` entities, autogenerate-able
    exactly like `RLS_POLICY_REGISTRY` (register them in `alembic/env.py` alongside
    the policies via `register_entities(..., entity_types=[PGFunction])`).
  * `CURRENT_USER_ID_SQL` / `IS_ACTIVE_WINGPERSON_SQL` — the raw `CREATE OR REPLACE
    FUNCTION` strings for a hand-added `op.execute(...)` block in the migration if
    the team prefers explicit DDL over an autogenerated diff.

Contract notes
--------------
* The GUC is `app.user_id` (a UUID string), set by `provide_transaction` /
  `rls_transaction` (`app/utils/deps.py`) on the NON-superuser `pear_app`
  connection (no `SET ROLE` — the role is `pear_app` natively). This mirrors
  Supabase's `auth.uid()` reading `request.jwt.claims`.
* `current_user_id()` uses `current_setting('app.user_id', true)` (the `true`
  = "missing_ok", returns NULL instead of erroring) so that an unset GUC yields
  NULL and every `= current_user_id()` comparison is NULL/false — policies
  **fail closed** for an unauthenticated session.
* `is_active_wingperson()` is ported from
  `supabase/migrations/20260426030000_winger_photo_rls.sql`, with `auth.uid()`
  swapped for `public.current_user_id()`.

IMPORTANT — enum label translation
----------------------------------
The Supabase schema used a native `public.wingperson_status` enum whose labels are
lowercase (`'active'`). The Litestar backend stores that column as TEXT via
`TextEnum`, which persists the enum's **`.name`** (UPPERCASE) — so the live column
value is `'ACTIVE'`, not `'active'`. The ported SQL therefore compares against
`WingpersonStatus.ACTIVE.name`. We interpolate it from the enum (rather than
hard-coding the literal) so the policy SQL can never drift from the model.
"""

from __future__ import annotations

from alembic_utils.pg_function import PGFunction

from app.domain.contacts.enums import WingpersonStatus

# The DB literal the `wingperson_status` TEXT column actually holds for "active".
# (TextEnum stores `.name`, so this is "ACTIVE" — NOT the Supabase "active".)
_ACTIVE_WINGPERSON_STATUS: str = WingpersonStatus.ACTIVE.name


# ── public.current_user_id() ─────────────────────────────────────────────────
# App-managed replacement for Supabase `auth.uid()`. Reads the `app.user_id` GUC
# set by the per-request transaction. `missing_ok = true` => NULL when unset, so
# policies fail closed for unauthenticated sessions.
CURRENT_USER_ID_SQL = """
CREATE OR REPLACE FUNCTION public.current_user_id()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
  SELECT NULLIF(current_setting('app.user_id', true), '')::uuid
$$;
""".strip()


# ── public.is_system_mode() ──────────────────────────────────────────────────
# The trusted-operation RLS bypass. `app.is_system_mode` is set true ONLY by
# `AuthService` (first-login bootstrap, before any `app.user_id` exists) and by
# system/worker jobs; the normal request path defensively forces it false (see
# `provide_transaction`). Every Pear policy ORs `public.is_system_mode()` ahead of
# its relationship condition so those trusted operations can write. `missing_ok =
# true` + the `nullif(...,'')` guard => false when unset/empty, so the escape is
# closed by default and policies fail closed for ordinary unauthenticated sessions.
IS_SYSTEM_MODE_SQL = """
CREATE OR REPLACE FUNCTION public.is_system_mode()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT coalesce(nullif(current_setting('app.is_system_mode', true), '')::boolean, false)
$$;
""".strip()


# ── public.is_active_wingperson(_dater uuid) ─────────────────────────────────
# Ported verbatim from 20260426030000_winger_photo_rls.sql with:
#   auth.uid()          -> public.current_user_id()
#   wingperson_status = 'active'  ->  = '<TextEnum name>'  (i.e. 'ACTIVE')
IS_ACTIVE_WINGPERSON_SQL = f"""
CREATE OR REPLACE FUNCTION public.is_active_wingperson(_dater uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.contacts
    WHERE user_id = _dater
      AND winger_id = public.current_user_id()
      AND wingperson_status = '{_ACTIVE_WINGPERSON_STATUS}'
  );
$$;
""".strip()


# ── alembic_utils entities (autogenerate-friendly) ───────────────────────────
# `signature` is the function's call signature; `definition` is everything from
# `returns` onward (PGFunction.from_sql parses on the `returns` keyword).
CURRENT_USER_ID_FN = PGFunction(
    schema="public",
    signature="current_user_id()",
    definition="""
        returns uuid
        language sql
        stable
        as $$
          select nullif(current_setting('app.user_id', true), '')::uuid
        $$
    """,
)

IS_SYSTEM_MODE_FN = PGFunction(
    schema="public",
    signature="is_system_mode()",
    definition="""
        returns boolean
        language sql
        stable
        as $$
          select coalesce(nullif(current_setting('app.is_system_mode', true), '')::boolean, false)
        $$
    """,
)

IS_ACTIVE_WINGPERSON_FN = PGFunction(
    schema="public",
    signature="is_active_wingperson(_dater uuid)",
    definition=f"""
        returns boolean
        language sql
        stable
        security invoker
        set search_path = public
        as $$
          select exists (
            select 1 from public.contacts
            where user_id = _dater
              and winger_id = public.current_user_id()
              and wingperson_status = '{_ACTIVE_WINGPERSON_STATUS}'
          );
        $$
    """,
)


# Consumed by alembic/env.py (parallel to RLS_POLICY_REGISTRY).
# `current_user_id` MUST be created before any policy that calls it, and before
# `is_active_wingperson` (which depends on it) — list it first. `is_system_mode`
# is standalone but every policy ORs it, so it too must exist before the policies.
RLS_FUNCTION_REGISTRY: list[PGFunction] = [
    CURRENT_USER_ID_FN,
    IS_SYSTEM_MODE_FN,
    IS_ACTIVE_WINGPERSON_FN,
]


__all__ = [
    "CURRENT_USER_ID_FN",
    "CURRENT_USER_ID_SQL",
    "IS_ACTIVE_WINGPERSON_FN",
    "IS_ACTIVE_WINGPERSON_SQL",
    "IS_SYSTEM_MODE_FN",
    "IS_SYSTEM_MODE_SQL",
    "RLS_FUNCTION_REGISTRY",
]
