"""add wingperson invite tokens rls policies

Revision ID: c874be458302
Revises: 4c8120f7b0b7
Create Date: 2026-07-10 20:56:18.080006+00:00

"""

from typing import Sequence

from alembic_utils.pg_policy import PGPolicy

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c874be458302"
down_revision: str | None = "4c8120f7b0b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_wingperson_invite_tokens_wingperson_invite_tokens_select = PGPolicy(
        schema="public",
        signature="wingperson_invite_tokens_select",
        on_entity="public.wingperson_invite_tokens",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR true)",
    )
    op.create_entity(public_wingperson_invite_tokens_wingperson_invite_tokens_select)

    public_wingperson_invite_tokens_wingperson_invite_tokens_insert = PGPolicy(
        schema="public",
        signature="wingperson_invite_tokens_insert",
        on_entity="public.wingperson_invite_tokens",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR true)",
    )
    op.create_entity(public_wingperson_invite_tokens_wingperson_invite_tokens_insert)

    public_wingperson_invite_tokens_wingperson_invite_tokens_update = PGPolicy(
        schema="public",
        signature="wingperson_invite_tokens_update",
        on_entity="public.wingperson_invite_tokens",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR true)\n        WITH CHECK (public.is_system_mode() OR true)",
    )
    op.create_entity(public_wingperson_invite_tokens_wingperson_invite_tokens_update)

    op.enable_rls("public", "wingperson_invite_tokens")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.disable_rls("public", "wingperson_invite_tokens")
    public_wingperson_invite_tokens_wingperson_invite_tokens_update = PGPolicy(
        schema="public",
        signature="wingperson_invite_tokens_update",
        on_entity="public.wingperson_invite_tokens",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR true)\n        WITH CHECK (public.is_system_mode() OR true)",
    )
    op.drop_entity(public_wingperson_invite_tokens_wingperson_invite_tokens_update)

    public_wingperson_invite_tokens_wingperson_invite_tokens_insert = PGPolicy(
        schema="public",
        signature="wingperson_invite_tokens_insert",
        on_entity="public.wingperson_invite_tokens",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR true)",
    )
    op.drop_entity(public_wingperson_invite_tokens_wingperson_invite_tokens_insert)

    public_wingperson_invite_tokens_wingperson_invite_tokens_select = PGPolicy(
        schema="public",
        signature="wingperson_invite_tokens_select",
        on_entity="public.wingperson_invite_tokens",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR true)",
    )
    op.drop_entity(public_wingperson_invite_tokens_wingperson_invite_tokens_select)

    # ### end Alembic commands ###
