"""add profile deactivated_at and auth identity apple refresh token

Revision ID: a774a0162de1
Revises: f41d2e8068fa
Create Date: 2026-07-09 20:42:46.689572+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a774a0162de1"
down_revision: str | None = "f41d2e8068fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("auth_identities", sa.Column("apple_refresh_token", sa.Text(), nullable=True))
    op.add_column("profiles", sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "deactivated_at")
    op.drop_column("auth_identities", "apple_refresh_token")
    # ### end Alembic commands ###
