"""split decision unique constraint for multi-winger suggestions

Revision ID: 8cbb6402f2b9
Revises: 97fbccef7294
Create Date: 2026-07-01 21:19:09.235206+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cbb6402f2b9"
down_revision: str | None = "97fbccef7294"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("unique_actor_recipient"), "decisions", type_="unique")
    op.create_index(
        "unique_actor_recipient_decision",
        "decisions",
        ["actor_id", "recipient_id"],
        unique=True,
        postgresql_where=sa.text("suggested_by IS NULL"),
    )
    op.create_index(
        "unique_actor_recipient_suggestion",
        "decisions",
        ["actor_id", "recipient_id", "suggested_by"],
        unique=True,
        postgresql_where=sa.text("suggested_by IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_actor_recipient_suggestion",
        table_name="decisions",
        postgresql_where=sa.text("suggested_by IS NOT NULL"),
    )
    op.drop_index(
        "unique_actor_recipient_decision", table_name="decisions", postgresql_where=sa.text("suggested_by IS NULL")
    )
    op.create_unique_constraint(
        op.f("unique_actor_recipient"), "decisions", ["actor_id", "recipient_id"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
