"""seed prompt templates

Revision ID: 89a26f2a9010
Revises: e46068a576fd
Create Date: 2026-06-13 20:17:06.991985+00:00

Reference-data migration: populates `prompt_templates` with the Hinge-style
profile prompt questions. Ported verbatim from the legacy Supabase seed
(`app/scripts/seed-local.ts` -> `PROMPT_QUESTIONS`), which is the source of truth
for the client-facing prompt set. Keeping these as a data migration (not a dev
seed script) means every environment — local, CI, prod — gets the same template
ids/rows deterministically as part of `alembic upgrade head`.

`profile_prompts.prompt_template_id` is a NOT NULL FK to this table, so the app
cannot create a single dater prompt until these rows exist.

The PK `id` is generated by `gen_random_uuid()` (built-in, PG13+); `created_at`/
`updated_at` fall back to the table's `now()` server defaults.
"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89a26f2a9010"
down_revision: str | None = "e46068a576fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Source of truth: app/scripts/seed-local.ts (PROMPT_QUESTIONS). Order preserved.
PROMPT_QUESTIONS: list[str] = [
    "The way to my heart is…",
    "A perfect Sunday looks like…",
    "My love language is…",
    "I get way too excited about…",
    "The most spontaneous thing I've done…",
    "Two truths and a lie…",
    "My friends would describe me as…",
    "I'm looking for someone who…",
    "Unpopular opinion I hold…",
    "My go-to karaoke song…",
]


def upgrade() -> None:
    # `prompt_templates.id` has no server-side default (the ORM fills it with a
    # Python-side uuid4), so generate ids in SQL with the built-in
    # `gen_random_uuid()`. `created_at`/`updated_at` use their `now()` defaults.
    bind = op.get_bind()
    bind.execute(
        sa.text("INSERT INTO prompt_templates (id, question) VALUES (gen_random_uuid(), :question)"),
        [{"question": question} for question in PROMPT_QUESTIONS],
    )


def downgrade() -> None:
    # Remove exactly the rows this migration seeded.
    bind = op.get_bind()
    bind.execute(
        sa.text("DELETE FROM prompt_templates WHERE question = ANY(:questions)"),
        {"questions": PROMPT_QUESTIONS},
    )
