"""rls: declarative co-located policies

Revision ID: 4781fa1bd8e5
Revises: 9b8becc20c04
Create Date: 2026-06-30 18:14:09.918726+00:00

"""

from typing import Sequence

from alembic_utils.pg_policy import PGPolicy

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4781fa1bd8e5"
down_revision: str | None = "9b8becc20c04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_messages_messages_select = PGPolicy(
        schema="public",
        signature="messages_select",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR EXISTS (SELECT 1 FROM public.matches m WHERE m.id = messages.match_id AND public.current_user_id() IN (m.user_a_id, m.user_b_id)))",
    )
    op.replace_entity(public_messages_messages_select)

    public_messages_messages_insert = PGPolicy(
        schema="public",
        signature="messages_insert",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR messages.sender_id = public.current_user_id())",
    )
    op.replace_entity(public_messages_messages_insert)

    public_messages_messages_update = PGPolicy(
        schema="public",
        signature="messages_update",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR messages.sender_id = public.current_user_id())\n        WITH CHECK (public.is_system_mode() OR messages.sender_id = public.current_user_id())",
    )
    op.replace_entity(public_messages_messages_update)

    public_dating_profiles_dating_profiles_select = PGPolicy(
        schema="public",
        signature="dating_profiles_select",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR public.current_user_id() IS NOT NULL)",
    )
    op.replace_entity(public_dating_profiles_dating_profiles_select)

    public_dating_profiles_dating_profiles_update = PGPolicy(
        schema="public",
        signature="dating_profiles_update",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR dating_profiles.user_id = public.current_user_id())\n        WITH CHECK (public.is_system_mode() OR dating_profiles.user_id = public.current_user_id())",
    )
    op.replace_entity(public_dating_profiles_dating_profiles_update)

    public_contacts_contacts_update = PGPolicy(
        schema="public",
        signature="contacts_update",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (contacts.user_id = public.current_user_id() OR contacts.winger_id = public.current_user_id()))\n        WITH CHECK (public.is_system_mode() OR (contacts.user_id = public.current_user_id() OR contacts.winger_id = public.current_user_id()))",
    )
    op.replace_entity(public_contacts_contacts_update)

    public_matches_matches_select = PGPolicy(
        schema="public",
        signature="matches_select",
        on_entity="public.matches",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR public.current_user_id() IN (matches.user_a_id, matches.user_b_id))",
    )
    op.replace_entity(public_matches_matches_select)

    public_matches_matches_insert = PGPolicy(
        schema="public",
        signature="matches_insert",
        on_entity="public.matches",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR false)",
    )
    op.replace_entity(public_matches_matches_insert)

    public_decisions_decisions_insert = PGPolicy(
        schema="public",
        signature="decisions_insert",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (decisions.actor_id = public.current_user_id() OR public.is_active_wingperson(decisions.actor_id)))",
    )
    op.replace_entity(public_decisions_decisions_insert)

    public_decisions_decisions_update = PGPolicy(
        schema="public",
        signature="decisions_update",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR decisions.actor_id = public.current_user_id())\n        WITH CHECK (public.is_system_mode() OR decisions.actor_id = public.current_user_id())",
    )
    op.replace_entity(public_decisions_decisions_update)

    public_prompt_templates_prompt_templates_select = PGPolicy(
        schema="public",
        signature="prompt_templates_select",
        on_entity="public.prompt_templates",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR public.current_user_id() IS NOT NULL)",
    )
    op.replace_entity(public_prompt_templates_prompt_templates_select)

    public_prompt_templates_prompt_templates_insert = PGPolicy(
        schema="public",
        signature="prompt_templates_insert",
        on_entity="public.prompt_templates",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR false)",
    )
    op.create_entity(public_prompt_templates_prompt_templates_insert)

    public_prompt_templates_prompt_templates_update = PGPolicy(
        schema="public",
        signature="prompt_templates_update",
        on_entity="public.prompt_templates",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR false)\n        WITH CHECK (public.is_system_mode() OR false)",
    )
    op.create_entity(public_prompt_templates_prompt_templates_update)

    public_prompt_templates_prompt_templates_delete = PGPolicy(
        schema="public",
        signature="prompt_templates_delete",
        on_entity="public.prompt_templates",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR false)",
    )
    op.create_entity(public_prompt_templates_prompt_templates_delete)

    public_profile_prompts_profile_prompts_select = PGPolicy(
        schema="public",
        signature="profile_prompts_select",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR public.current_user_id() IS NOT NULL)",
    )
    op.create_entity(public_profile_prompts_profile_prompts_select)

    public_profile_prompts_profile_prompts_insert = PGPolicy(
        schema="public",
        signature="profile_prompts_insert",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR profile_prompts.owner_id = public.current_user_id())",
    )
    op.create_entity(public_profile_prompts_profile_prompts_insert)

    public_profile_prompts_profile_prompts_update = PGPolicy(
        schema="public",
        signature="profile_prompts_update",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR profile_prompts.owner_id = public.current_user_id())\n        WITH CHECK (public.is_system_mode() OR profile_prompts.owner_id = public.current_user_id())",
    )
    op.create_entity(public_profile_prompts_profile_prompts_update)

    public_profile_prompts_profile_prompts_delete = PGPolicy(
        schema="public",
        signature="profile_prompts_delete",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR profile_prompts.owner_id = public.current_user_id())",
    )
    op.create_entity(public_profile_prompts_profile_prompts_delete)

    public_prompt_responses_prompt_responses_update = PGPolicy(
        schema="public",
        signature="prompt_responses_update",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR prompt_responses.profile_owner_id = public.current_user_id())\n        WITH CHECK (public.is_system_mode() OR prompt_responses.profile_owner_id = public.current_user_id())",
    )
    op.replace_entity(public_prompt_responses_prompt_responses_update)

    public_profile_photos_profile_photos_select = PGPolicy(
        schema="public",
        signature="profile_photos_select",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR public.current_user_id() IS NOT NULL)",
    )
    op.create_entity(public_profile_photos_profile_photos_select)

    public_profile_photos_profile_photos_insert = PGPolicy(
        schema="public",
        signature="profile_photos_insert",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (profile_photos.owner_id = public.current_user_id() OR public.is_active_wingperson(profile_photos.owner_id)))",
    )
    op.create_entity(public_profile_photos_profile_photos_insert)

    public_profile_photos_profile_photos_update = PGPolicy(
        schema="public",
        signature="profile_photos_update",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (profile_photos.owner_id = public.current_user_id() OR public.is_active_wingperson(profile_photos.owner_id)))\n        WITH CHECK (public.is_system_mode() OR (profile_photos.owner_id = public.current_user_id() OR public.is_active_wingperson(profile_photos.owner_id)))",
    )
    op.create_entity(public_profile_photos_profile_photos_update)

    public_profile_photos_profile_photos_delete = PGPolicy(
        schema="public",
        signature="profile_photos_delete",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (profile_photos.owner_id = public.current_user_id() OR public.is_active_wingperson(profile_photos.owner_id)))",
    )
    op.create_entity(public_profile_photos_profile_photos_delete)

    public_magic_link_tokens_magic_link_tokens_select = PGPolicy(
        schema="public",
        signature="magic_link_tokens_select",
        on_entity="public.magic_link_tokens",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR true)",
    )
    op.replace_entity(public_magic_link_tokens_magic_link_tokens_select)

    public_magic_link_tokens_magic_link_tokens_insert = PGPolicy(
        schema="public",
        signature="magic_link_tokens_insert",
        on_entity="public.magic_link_tokens",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR true)",
    )
    op.replace_entity(public_magic_link_tokens_magic_link_tokens_insert)

    public_magic_link_tokens_magic_link_tokens_update = PGPolicy(
        schema="public",
        signature="magic_link_tokens_update",
        on_entity="public.magic_link_tokens",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR true)\n        WITH CHECK (public.is_system_mode() OR true)",
    )
    op.replace_entity(public_magic_link_tokens_magic_link_tokens_update)

    public_media_media_select = PGPolicy(
        schema="public",
        signature="media_select",
        on_entity="public.media",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (owner_id = public.current_user_id()\n          OR public.is_active_wingperson(owner_id)\n          OR EXISTS (\n            SELECT 1\n            FROM public.profile_photos pp\n            JOIN public.dating_profiles dp ON dp.id = pp.dating_profile_id\n            WHERE pp.media_id = media.id\n              AND (\n                dp.user_id = public.current_user_id()\n                OR pp.suggester_id = public.current_user_id()\n                OR (dp.is_active = true AND pp.state = 'APPROVED')\n              )\n          )\n          OR EXISTS (\n            SELECT 1 FROM public.profiles p WHERE p.avatar_media_id = media.id\n          )))",
    )
    op.replace_entity(public_media_media_select)

    public_media_media_insert = PGPolicy(
        schema="public",
        signature="media_insert",
        on_entity="public.media",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (media.owner_id = public.current_user_id() OR public.is_active_wingperson(media.owner_id)))",
    )
    op.replace_entity(public_media_media_insert)

    public_media_media_update = PGPolicy(
        schema="public",
        signature="media_update",
        on_entity="public.media",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (media.owner_id = public.current_user_id() OR public.is_active_wingperson(media.owner_id)))\n        WITH CHECK (public.is_system_mode() OR (media.owner_id = public.current_user_id() OR public.is_active_wingperson(media.owner_id)))",
    )
    op.replace_entity(public_media_media_update)

    public_media_media_delete = PGPolicy(
        schema="public",
        signature="media_delete",
        on_entity="public.media",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (media.owner_id = public.current_user_id() OR public.is_active_wingperson(media.owner_id)))",
    )
    op.replace_entity(public_media_media_delete)

    public_profile_photos_profile_photos_public_select = PGPolicy(
        schema="public",
        signature="profile_photos_public_select",
        on_entity="public.profile_photos",
        definition="as PERMISSIVE for SELECT to pear_app using ((suggester_id = current_user_id()) OR (EXISTS ( SELECT 1\n   FROM dating_profiles dp\n  WHERE ((dp.id = profile_photos.dating_profile_id) AND (dp.is_active = true) AND (profile_photos.state = 'APPROVED'::text)))))",
    )
    op.drop_entity(public_profile_photos_profile_photos_public_select)

    public_profile_prompts_profile_prompts_public_select = PGPolicy(
        schema="public",
        signature="profile_prompts_public_select",
        on_entity="public.profile_prompts",
        definition="as PERMISSIVE for SELECT to pear_app using (EXISTS ( SELECT 1\n   FROM dating_profiles dp\n  WHERE ((dp.id = profile_prompts.dating_profile_id) AND (dp.is_active = true))))",
    )
    op.drop_entity(public_profile_prompts_profile_prompts_public_select)

    public_profile_prompts_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.profile_prompts",
        definition="as PERMISSIVE for ALL to pear_app using (is_system_mode() OR (owner_id = current_user_id())) with check (is_system_mode() OR (owner_id = current_user_id()))",
    )
    op.drop_entity(public_profile_prompts_user_scope_policy)

    public_profile_photos_wingperson_scope_policy = PGPolicy(
        schema="public",
        signature="wingperson_scope_policy",
        on_entity="public.profile_photos",
        definition="as PERMISSIVE for ALL to pear_app using (is_system_mode() OR (owner_id = current_user_id()) OR is_active_wingperson(owner_id)) with check (is_system_mode() OR (owner_id = current_user_id()) OR is_active_wingperson(owner_id))",
    )
    op.drop_entity(public_profile_photos_wingperson_scope_policy)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_profile_photos_wingperson_scope_policy = PGPolicy(
        schema="public",
        signature="wingperson_scope_policy",
        on_entity="public.profile_photos",
        definition="as PERMISSIVE for ALL to pear_app using (is_system_mode() OR (owner_id = current_user_id()) OR is_active_wingperson(owner_id)) with check (is_system_mode() OR (owner_id = current_user_id()) OR is_active_wingperson(owner_id))",
    )
    op.create_entity(public_profile_photos_wingperson_scope_policy)

    public_profile_prompts_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.profile_prompts",
        definition="as PERMISSIVE for ALL to pear_app using (is_system_mode() OR (owner_id = current_user_id())) with check (is_system_mode() OR (owner_id = current_user_id()))",
    )
    op.create_entity(public_profile_prompts_user_scope_policy)

    public_profile_prompts_profile_prompts_public_select = PGPolicy(
        schema="public",
        signature="profile_prompts_public_select",
        on_entity="public.profile_prompts",
        definition="as PERMISSIVE for SELECT to pear_app using (EXISTS ( SELECT 1\n   FROM dating_profiles dp\n  WHERE ((dp.id = profile_prompts.dating_profile_id) AND (dp.is_active = true))))",
    )
    op.create_entity(public_profile_prompts_profile_prompts_public_select)

    public_profile_photos_profile_photos_public_select = PGPolicy(
        schema="public",
        signature="profile_photos_public_select",
        on_entity="public.profile_photos",
        definition="as PERMISSIVE for SELECT to pear_app using ((suggester_id = current_user_id()) OR (EXISTS ( SELECT 1\n   FROM dating_profiles dp\n  WHERE ((dp.id = profile_photos.dating_profile_id) AND (dp.is_active = true) AND (profile_photos.state = 'APPROVED'::text)))))",
    )
    op.create_entity(public_profile_photos_profile_photos_public_select)

    public_media_media_delete = PGPolicy(
        schema="public",
        signature="media_delete",
        on_entity="public.media",
        definition="as PERMISSIVE for DELETE to pear_app using (is_system_mode() OR (owner_id = current_user_id()) OR is_active_wingperson(owner_id))",
    )
    op.replace_entity(public_media_media_delete)
    public_media_media_update = PGPolicy(
        schema="public",
        signature="media_update",
        on_entity="public.media",
        definition="as PERMISSIVE for UPDATE to pear_app using (is_system_mode() OR (owner_id = current_user_id()) OR is_active_wingperson(owner_id))",
    )
    op.replace_entity(public_media_media_update)
    public_media_media_insert = PGPolicy(
        schema="public",
        signature="media_insert",
        on_entity="public.media",
        definition="as PERMISSIVE for INSERT to pear_app with check (is_system_mode() OR (owner_id = current_user_id()) OR is_active_wingperson(owner_id))",
    )
    op.replace_entity(public_media_media_insert)
    public_media_media_select = PGPolicy(
        schema="public",
        signature="media_select",
        on_entity="public.media",
        definition="as PERMISSIVE for SELECT to pear_app using (is_system_mode() OR (owner_id = current_user_id()) OR is_active_wingperson(owner_id) OR (EXISTS ( SELECT 1\n   FROM (profile_photos pp\n     JOIN dating_profiles dp ON ((dp.id = pp.dating_profile_id)))\n  WHERE ((pp.media_id = media.id) AND ((dp.user_id = current_user_id()) OR (pp.suggester_id = current_user_id()) OR ((dp.is_active = true) AND (pp.state = 'APPROVED'::text)))))) OR (EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE (p.avatar_media_id = media.id))))",
    )
    op.replace_entity(public_media_media_select)
    public_magic_link_tokens_magic_link_tokens_update = PGPolicy(
        schema="public",
        signature="magic_link_tokens_update",
        on_entity="public.magic_link_tokens",
        definition="as PERMISSIVE for UPDATE to pear_app using (true)",
    )
    op.replace_entity(public_magic_link_tokens_magic_link_tokens_update)
    public_magic_link_tokens_magic_link_tokens_insert = PGPolicy(
        schema="public",
        signature="magic_link_tokens_insert",
        on_entity="public.magic_link_tokens",
        definition="as PERMISSIVE for INSERT to pear_app with check (true)",
    )
    op.replace_entity(public_magic_link_tokens_magic_link_tokens_insert)
    public_magic_link_tokens_magic_link_tokens_select = PGPolicy(
        schema="public",
        signature="magic_link_tokens_select",
        on_entity="public.magic_link_tokens",
        definition="as PERMISSIVE for SELECT to pear_app using (true)",
    )
    op.replace_entity(public_magic_link_tokens_magic_link_tokens_select)
    public_profile_photos_profile_photos_delete = PGPolicy(
        schema="public",
        signature="profile_photos_delete",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (profile_photos.owner_id = public.current_user_id() OR public.is_active_wingperson(profile_photos.owner_id)))",
    )
    op.drop_entity(public_profile_photos_profile_photos_delete)

    public_profile_photos_profile_photos_update = PGPolicy(
        schema="public",
        signature="profile_photos_update",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (profile_photos.owner_id = public.current_user_id() OR public.is_active_wingperson(profile_photos.owner_id)))\n        WITH CHECK (public.is_system_mode() OR (profile_photos.owner_id = public.current_user_id() OR public.is_active_wingperson(profile_photos.owner_id)))",
    )
    op.drop_entity(public_profile_photos_profile_photos_update)

    public_profile_photos_profile_photos_insert = PGPolicy(
        schema="public",
        signature="profile_photos_insert",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (profile_photos.owner_id = public.current_user_id() OR public.is_active_wingperson(profile_photos.owner_id)))",
    )
    op.drop_entity(public_profile_photos_profile_photos_insert)

    public_profile_photos_profile_photos_select = PGPolicy(
        schema="public",
        signature="profile_photos_select",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR public.current_user_id() IS NOT NULL)",
    )
    op.drop_entity(public_profile_photos_profile_photos_select)

    public_prompt_responses_prompt_responses_update = PGPolicy(
        schema="public",
        signature="prompt_responses_update",
        on_entity="public.prompt_responses",
        definition="as PERMISSIVE for UPDATE to pear_app using (is_system_mode() OR (profile_owner_id = current_user_id()))",
    )
    op.replace_entity(public_prompt_responses_prompt_responses_update)
    public_profile_prompts_profile_prompts_delete = PGPolicy(
        schema="public",
        signature="profile_prompts_delete",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR profile_prompts.owner_id = public.current_user_id())",
    )
    op.drop_entity(public_profile_prompts_profile_prompts_delete)

    public_profile_prompts_profile_prompts_update = PGPolicy(
        schema="public",
        signature="profile_prompts_update",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR profile_prompts.owner_id = public.current_user_id())\n        WITH CHECK (public.is_system_mode() OR profile_prompts.owner_id = public.current_user_id())",
    )
    op.drop_entity(public_profile_prompts_profile_prompts_update)

    public_profile_prompts_profile_prompts_insert = PGPolicy(
        schema="public",
        signature="profile_prompts_insert",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR profile_prompts.owner_id = public.current_user_id())",
    )
    op.drop_entity(public_profile_prompts_profile_prompts_insert)

    public_profile_prompts_profile_prompts_select = PGPolicy(
        schema="public",
        signature="profile_prompts_select",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR public.current_user_id() IS NOT NULL)",
    )
    op.drop_entity(public_profile_prompts_profile_prompts_select)

    public_prompt_templates_prompt_templates_delete = PGPolicy(
        schema="public",
        signature="prompt_templates_delete",
        on_entity="public.prompt_templates",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR false)",
    )
    op.drop_entity(public_prompt_templates_prompt_templates_delete)

    public_prompt_templates_prompt_templates_update = PGPolicy(
        schema="public",
        signature="prompt_templates_update",
        on_entity="public.prompt_templates",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR false)\n        WITH CHECK (public.is_system_mode() OR false)",
    )
    op.drop_entity(public_prompt_templates_prompt_templates_update)

    public_prompt_templates_prompt_templates_insert = PGPolicy(
        schema="public",
        signature="prompt_templates_insert",
        on_entity="public.prompt_templates",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR false)",
    )
    op.drop_entity(public_prompt_templates_prompt_templates_insert)

    public_prompt_templates_prompt_templates_select = PGPolicy(
        schema="public",
        signature="prompt_templates_select",
        on_entity="public.prompt_templates",
        definition="as PERMISSIVE for SELECT to pear_app using (true)",
    )
    op.replace_entity(public_prompt_templates_prompt_templates_select)
    public_decisions_decisions_update = PGPolicy(
        schema="public",
        signature="decisions_update",
        on_entity="public.decisions",
        definition="as PERMISSIVE for UPDATE to pear_app using (is_system_mode() OR (actor_id = current_user_id()))",
    )
    op.replace_entity(public_decisions_decisions_update)
    public_decisions_decisions_insert = PGPolicy(
        schema="public",
        signature="decisions_insert",
        on_entity="public.decisions",
        definition="as PERMISSIVE for INSERT to pear_app with check (is_system_mode() OR ((actor_id = current_user_id()) OR ((suggested_by = current_user_id()) AND (EXISTS ( SELECT 1\n   FROM contacts c\n  WHERE ((c.user_id = decisions.actor_id) AND (c.winger_id = current_user_id()) AND (c.state = 'ACTIVE'::text)))))))",
    )
    op.replace_entity(public_decisions_decisions_insert)
    public_matches_matches_insert = PGPolicy(
        schema="public",
        signature="matches_insert",
        on_entity="public.matches",
        definition="as PERMISSIVE for INSERT to pear_app with check (is_system_mode())",
    )
    op.replace_entity(public_matches_matches_insert)
    public_matches_matches_select = PGPolicy(
        schema="public",
        signature="matches_select",
        on_entity="public.matches",
        definition="as PERMISSIVE for SELECT to pear_app using (is_system_mode() OR ((user_a_id = current_user_id()) OR (user_b_id = current_user_id())))",
    )
    op.replace_entity(public_matches_matches_select)
    public_contacts_contacts_update = PGPolicy(
        schema="public",
        signature="contacts_update",
        on_entity="public.contacts",
        definition="as PERMISSIVE for UPDATE to pear_app using (is_system_mode() OR ((user_id = current_user_id()) OR (winger_id = current_user_id())))",
    )
    op.replace_entity(public_contacts_contacts_update)
    public_dating_profiles_dating_profiles_update = PGPolicy(
        schema="public",
        signature="dating_profiles_update",
        on_entity="public.dating_profiles",
        definition="as PERMISSIVE for UPDATE to pear_app using (is_system_mode() OR (user_id = current_user_id()))",
    )
    op.replace_entity(public_dating_profiles_dating_profiles_update)
    public_dating_profiles_dating_profiles_select = PGPolicy(
        schema="public",
        signature="dating_profiles_select",
        on_entity="public.dating_profiles",
        definition="as PERMISSIVE for SELECT to pear_app using (is_system_mode() OR ((is_active = true) OR (user_id = current_user_id())))",
    )
    op.replace_entity(public_dating_profiles_dating_profiles_select)
    public_messages_messages_update = PGPolicy(
        schema="public",
        signature="messages_update",
        on_entity="public.messages",
        definition="as PERMISSIVE for UPDATE to pear_app using (is_system_mode() OR (sender_id = current_user_id()))",
    )
    op.replace_entity(public_messages_messages_update)
    public_messages_messages_insert = PGPolicy(
        schema="public",
        signature="messages_insert",
        on_entity="public.messages",
        definition="as PERMISSIVE for INSERT to pear_app with check (is_system_mode() OR ((sender_id = current_user_id()) AND (EXISTS ( SELECT 1\n   FROM matches m\n  WHERE ((m.id = messages.match_id) AND ((m.user_a_id = current_user_id()) OR (m.user_b_id = current_user_id())))))))",
    )
    op.replace_entity(public_messages_messages_insert)
    public_messages_messages_select = PGPolicy(
        schema="public",
        signature="messages_select",
        on_entity="public.messages",
        definition="as PERMISSIVE for SELECT to pear_app using (is_system_mode() OR (EXISTS ( SELECT 1\n   FROM matches m\n  WHERE ((m.id = messages.match_id) AND ((m.user_a_id = current_user_id()) OR (m.user_b_id = current_user_id()))))))",
    )
    op.replace_entity(public_messages_messages_select)
    # ### end Alembic commands ###
