"""matches insert policy: mutual-approved participant (replaces system-only)

Revision ID: d926750af59e
Revises: 4781fa1bd8e5
Create Date: 2026-06-30 20:13:44.725689+00:00

"""

from typing import Sequence

from alembic_utils.pg_policy import PGPolicy

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d926750af59e"
down_revision: str | None = "4781fa1bd8e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_matches_matches_insert = PGPolicy(
        schema="public",
        signature="matches_insert",
        on_entity="public.matches",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR public.current_user_id() IN (matches.user_a_id, matches.user_b_id) AND EXISTS (SELECT 1 FROM public.decisions d WHERE d.actor_id = matches.user_a_id AND d.recipient_id = matches.user_b_id AND d.state = 'APPROVED') AND EXISTS (SELECT 1 FROM public.decisions d WHERE d.actor_id = matches.user_b_id AND d.recipient_id = matches.user_a_id AND d.state = 'APPROVED'))",
    )
    op.replace_entity(public_matches_matches_insert)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_matches_matches_insert = PGPolicy(
        schema="public",
        signature="matches_insert",
        on_entity="public.matches",
        definition="as PERMISSIVE for INSERT to pear_app with check (is_system_mode() OR false)",
    )
    op.replace_entity(public_matches_matches_insert)
    # ### end Alembic commands ###
