"""add native_build_fingerprints table

Revision ID: 97fbccef7294
Revises: dccdc4d3bb22
Create Date: 2026-07-01 18:54:42.492211+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op
from app.platform.updates.enums import UpdatePlatform
from app.utils.sqids import SqidType
from app.utils.textenum import TextEnum

# revision identifiers, used by Alembic.
revision: str = "97fbccef7294"
down_revision: str | None = "dccdc4d3bb22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "native_build_fingerprints",
        sa.Column("platform", TextEnum(UpdatePlatform), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform"),
    )
    op.create_index(
        op.f("ix_native_build_fingerprints_deleted_at"), "native_build_fingerprints", ["deleted_at"], unique=False
    )

    # No RLS on this table — same call as `app_updates` (see
    # `20260701_1200_add_app_updates_table_ota_manifest_dccdc4d3bb22`): both
    # `/updates/native-build-fingerprint` routes are unauthenticated and
    # root-mounted, with no per-request actor to scope a policy against.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_native_build_fingerprints_deleted_at"), table_name="native_build_fingerprints")
    op.drop_table("native_build_fingerprints")
    # ### end Alembic commands ###
