"""rls policies and functions

Revision ID: 4a5166053ba0
Revises: e215e819cb18
Create Date: 2026-06-13 20:56:39.810318+00:00

"""

from typing import Sequence

from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_policy import PGPolicy

from alembic import op
from app.platform.base.rls_grants import app_grants_sql

# revision identifiers, used by Alembic.
revision: str = "4a5166053ba0"
down_revision: str | None = "e215e819cb18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_current_user_id = PGFunction(
        schema="public",
        signature="current_user_id()",
        definition="returns uuid\n        language sql\n        stable\n        as $$\n          select nullif(current_setting('app.user_id', true), '')::uuid\n        $$",
    )
    op.create_entity(public_current_user_id)

    public_is_system_mode = PGFunction(
        schema="public",
        signature="is_system_mode()",
        definition="returns boolean\n        language sql\n        stable\n        as $$\n          select coalesce(nullif(current_setting('app.is_system_mode', true), '')::boolean, false)\n        $$",
    )
    op.create_entity(public_is_system_mode)

    public_profiles_profiles_select = PGPolicy(
        schema="public",
        signature="profiles_select",
        on_entity="public.profiles",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (true)",
    )
    op.create_entity(public_profiles_profiles_select)

    public_prompt_templates_prompt_templates_select = PGPolicy(
        schema="public",
        signature="prompt_templates_select",
        on_entity="public.prompt_templates",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (true)",
    )
    op.create_entity(public_prompt_templates_prompt_templates_select)

    public_is_active_wingperson = PGFunction(
        schema="public",
        signature="is_active_wingperson(_dater uuid)",
        definition="returns boolean\n        language sql\n        stable\n        security invoker\n        set search_path = public\n        as $$\n          select exists (\n            select 1 from public.contacts\n            where user_id = _dater\n              and winger_id = public.current_user_id()\n              and wingperson_status = 'ACTIVE'\n          );\n        $$",
    )
    op.create_entity(public_is_active_wingperson)

    public_profiles_profiles_insert = PGPolicy(
        schema="public",
        signature="profiles_insert",
        on_entity="public.profiles",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (id = public.current_user_id()))",
    )
    op.create_entity(public_profiles_profiles_insert)

    public_profiles_profiles_update = PGPolicy(
        schema="public",
        signature="profiles_update",
        on_entity="public.profiles",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (id = public.current_user_id()))",
    )
    op.create_entity(public_profiles_profiles_update)

    public_dating_profiles_dating_profiles_select = PGPolicy(
        schema="public",
        signature="dating_profiles_select",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (is_active = true OR user_id = public.current_user_id()))",
    )
    op.create_entity(public_dating_profiles_dating_profiles_select)

    public_dating_profiles_dating_profiles_insert = PGPolicy(
        schema="public",
        signature="dating_profiles_insert",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.create_entity(public_dating_profiles_dating_profiles_insert)

    public_dating_profiles_dating_profiles_update = PGPolicy(
        schema="public",
        signature="dating_profiles_update",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.create_entity(public_dating_profiles_dating_profiles_update)

    public_dating_profiles_dating_profiles_delete = PGPolicy(
        schema="public",
        signature="dating_profiles_delete",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.create_entity(public_dating_profiles_dating_profiles_delete)

    public_profile_photos_profile_photos_select = PGPolicy(
        schema="public",
        signature="profile_photos_select",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_photos.dating_profile_id\n              AND (\n                dp.user_id = public.current_user_id()\n                OR profile_photos.suggester_id = public.current_user_id()\n                OR (dp.is_active = true AND profile_photos.approved_at IS NOT NULL)\n              )\n          )\n        ))",
    )
    op.create_entity(public_profile_photos_profile_photos_select)

    public_profile_photos_profile_photos_insert = PGPolicy(
        schema="public",
        signature="profile_photos_insert",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_photos.dating_profile_id\n              AND (\n                dp.user_id = public.current_user_id()\n                OR (\n                  profile_photos.suggester_id = public.current_user_id()\n                  AND public.is_active_wingperson(dp.user_id)\n                )\n              )\n          )\n        ))",
    )
    op.create_entity(public_profile_photos_profile_photos_insert)

    public_profile_photos_profile_photos_update = PGPolicy(
        schema="public",
        signature="profile_photos_update",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_photos.dating_profile_id\n              AND dp.user_id = public.current_user_id()\n          )\n        ))",
    )
    op.create_entity(public_profile_photos_profile_photos_update)

    public_profile_photos_profile_photos_delete = PGPolicy(
        schema="public",
        signature="profile_photos_delete",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_photos.dating_profile_id\n              AND dp.user_id = public.current_user_id()\n          )\n          OR profile_photos.suggester_id = public.current_user_id()\n        ))",
    )
    op.create_entity(public_profile_photos_profile_photos_delete)

    public_profile_prompts_profile_prompts_select = PGPolicy(
        schema="public",
        signature="profile_prompts_select",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_prompts.dating_profile_id\n              AND (dp.is_active = true OR dp.user_id = public.current_user_id())\n          )\n        ))",
    )
    op.create_entity(public_profile_prompts_profile_prompts_select)

    public_profile_prompts_profile_prompts_insert = PGPolicy(
        schema="public",
        signature="profile_prompts_insert",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_prompts.dating_profile_id\n              AND dp.user_id = public.current_user_id()\n          )\n        ))",
    )
    op.create_entity(public_profile_prompts_profile_prompts_insert)

    public_profile_prompts_profile_prompts_update = PGPolicy(
        schema="public",
        signature="profile_prompts_update",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_prompts.dating_profile_id\n              AND dp.user_id = public.current_user_id()\n          )\n        ))",
    )
    op.create_entity(public_profile_prompts_profile_prompts_update)

    public_profile_prompts_profile_prompts_delete = PGPolicy(
        schema="public",
        signature="profile_prompts_delete",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_prompts.dating_profile_id\n              AND dp.user_id = public.current_user_id()\n          )\n        ))",
    )
    op.create_entity(public_profile_prompts_profile_prompts_delete)

    public_prompt_responses_prompt_responses_select = PGPolicy(
        schema="public",
        signature="prompt_responses_select",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          user_id = public.current_user_id()\n          OR EXISTS (\n            SELECT 1\n            FROM public.profile_prompts pp\n            JOIN public.dating_profiles dp ON dp.id = pp.dating_profile_id\n            WHERE pp.id = prompt_responses.profile_prompt_id\n              AND dp.user_id = public.current_user_id()\n          )\n        ))",
    )
    op.create_entity(public_prompt_responses_prompt_responses_select)

    public_prompt_responses_prompt_responses_insert = PGPolicy(
        schema="public",
        signature="prompt_responses_insert",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.create_entity(public_prompt_responses_prompt_responses_insert)

    public_prompt_responses_prompt_responses_update = PGPolicy(
        schema="public",
        signature="prompt_responses_update",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1\n            FROM public.profile_prompts pp\n            JOIN public.dating_profiles dp ON dp.id = pp.dating_profile_id\n            WHERE pp.id = prompt_responses.profile_prompt_id\n              AND dp.user_id = public.current_user_id()\n          )\n        ))",
    )
    op.create_entity(public_prompt_responses_prompt_responses_update)

    public_contacts_contacts_select = PGPolicy(
        schema="public",
        signature="contacts_select",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id() OR winger_id = public.current_user_id()))",
    )
    op.create_entity(public_contacts_contacts_select)

    public_contacts_contacts_insert = PGPolicy(
        schema="public",
        signature="contacts_insert",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.create_entity(public_contacts_contacts_insert)

    public_contacts_contacts_update = PGPolicy(
        schema="public",
        signature="contacts_update",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id() OR winger_id = public.current_user_id()))",
    )
    op.create_entity(public_contacts_contacts_update)

    public_contacts_contacts_delete = PGPolicy(
        schema="public",
        signature="contacts_delete",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.create_entity(public_contacts_contacts_delete)

    public_decisions_decisions_select = PGPolicy(
        schema="public",
        signature="decisions_select",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          actor_id = public.current_user_id()\n          OR recipient_id = public.current_user_id()\n          OR suggested_by = public.current_user_id()\n        ))",
    )
    op.create_entity(public_decisions_decisions_select)

    public_decisions_decisions_insert = PGPolicy(
        schema="public",
        signature="decisions_insert",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (\n          actor_id = public.current_user_id()\n          OR (\n            suggested_by = public.current_user_id()\n            AND EXISTS (\n              SELECT 1 FROM public.contacts c\n              WHERE c.user_id = decisions.actor_id\n                AND c.winger_id = public.current_user_id()\n                AND c.wingperson_status = 'ACTIVE'\n            )\n          )\n        ))",
    )
    op.create_entity(public_decisions_decisions_insert)

    public_decisions_decisions_update = PGPolicy(
        schema="public",
        signature="decisions_update",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (actor_id = public.current_user_id()))",
    )
    op.create_entity(public_decisions_decisions_update)

    public_matches_matches_select = PGPolicy(
        schema="public",
        signature="matches_select",
        on_entity="public.matches",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          user_a_id = public.current_user_id() OR user_b_id = public.current_user_id()\n        ))",
    )
    op.create_entity(public_matches_matches_select)

    public_matches_matches_insert = PGPolicy(
        schema="public",
        signature="matches_insert",
        on_entity="public.matches",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode())",
    )
    op.create_entity(public_matches_matches_insert)

    public_messages_messages_select = PGPolicy(
        schema="public",
        signature="messages_select",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.matches m\n            WHERE m.id = messages.match_id\n              AND (m.user_a_id = public.current_user_id() OR m.user_b_id = public.current_user_id())\n          )\n        ))",
    )
    op.create_entity(public_messages_messages_select)

    public_messages_messages_insert = PGPolicy(
        schema="public",
        signature="messages_insert",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (\n          sender_id = public.current_user_id()\n          AND EXISTS (\n            SELECT 1 FROM public.matches m\n            WHERE m.id = messages.match_id\n              AND (m.user_a_id = public.current_user_id() OR m.user_b_id = public.current_user_id())\n          )\n        ))",
    )
    op.create_entity(public_messages_messages_insert)

    public_messages_messages_update = PGPolicy(
        schema="public",
        signature="messages_update",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (sender_id = public.current_user_id()))",
    )
    op.create_entity(public_messages_messages_update)

    public_profile_reports_profile_reports_insert = PGPolicy(
        schema="public",
        signature="profile_reports_insert",
        on_entity="public.profile_reports",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (reporter_id = public.current_user_id()))",
    )
    op.create_entity(public_profile_reports_profile_reports_insert)

    op.enable_rls("public", "contacts")
    op.enable_rls("public", "dating_profiles")
    op.enable_rls("public", "decisions")
    op.enable_rls("public", "matches")
    op.enable_rls("public", "messages")
    op.enable_rls("public", "profile_photos")
    op.enable_rls("public", "profile_prompts")
    op.enable_rls("public", "profile_reports")
    op.enable_rls("public", "profiles")
    op.enable_rls("public", "prompt_responses")
    op.enable_rls("public", "prompt_templates")
    # ### end Alembic commands ###

    # ── pear_app GRANTs (privilege floor for RLS) ────────────────────────────
    # Re-assert the centralized grant block now that ALL objects exist: the auth
    # tables (migration e215e819cb18), every domain table, and the three RLS
    # helper functions created above. GRANTs are idempotent, and EXECUTE on the
    # functions is required so `pear_app` can call current_user_id() /
    # is_system_mode() / is_active_wingperson() from inside the policies. Guarded
    # on role existence. The `pear_app` role itself is created in the initial
    # migration's bootstrap block.
    op.execute(app_grants_sql())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.disable_rls("public", "prompt_templates")
    op.disable_rls("public", "prompt_responses")
    op.disable_rls("public", "profiles")
    op.disable_rls("public", "profile_reports")
    op.disable_rls("public", "profile_prompts")
    op.disable_rls("public", "profile_photos")
    op.disable_rls("public", "messages")
    op.disable_rls("public", "matches")
    op.disable_rls("public", "decisions")
    op.disable_rls("public", "dating_profiles")
    op.disable_rls("public", "contacts")
    public_profile_reports_profile_reports_insert = PGPolicy(
        schema="public",
        signature="profile_reports_insert",
        on_entity="public.profile_reports",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (reporter_id = public.current_user_id()))",
    )
    op.drop_entity(public_profile_reports_profile_reports_insert)

    public_messages_messages_update = PGPolicy(
        schema="public",
        signature="messages_update",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (sender_id = public.current_user_id()))",
    )
    op.drop_entity(public_messages_messages_update)

    public_messages_messages_insert = PGPolicy(
        schema="public",
        signature="messages_insert",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (\n          sender_id = public.current_user_id()\n          AND EXISTS (\n            SELECT 1 FROM public.matches m\n            WHERE m.id = messages.match_id\n              AND (m.user_a_id = public.current_user_id() OR m.user_b_id = public.current_user_id())\n          )\n        ))",
    )
    op.drop_entity(public_messages_messages_insert)

    public_messages_messages_select = PGPolicy(
        schema="public",
        signature="messages_select",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.matches m\n            WHERE m.id = messages.match_id\n              AND (m.user_a_id = public.current_user_id() OR m.user_b_id = public.current_user_id())\n          )\n        ))",
    )
    op.drop_entity(public_messages_messages_select)

    public_matches_matches_insert = PGPolicy(
        schema="public",
        signature="matches_insert",
        on_entity="public.matches",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode())",
    )
    op.drop_entity(public_matches_matches_insert)

    public_matches_matches_select = PGPolicy(
        schema="public",
        signature="matches_select",
        on_entity="public.matches",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          user_a_id = public.current_user_id() OR user_b_id = public.current_user_id()\n        ))",
    )
    op.drop_entity(public_matches_matches_select)

    public_decisions_decisions_update = PGPolicy(
        schema="public",
        signature="decisions_update",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (actor_id = public.current_user_id()))",
    )
    op.drop_entity(public_decisions_decisions_update)

    public_decisions_decisions_insert = PGPolicy(
        schema="public",
        signature="decisions_insert",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (\n          actor_id = public.current_user_id()\n          OR (\n            suggested_by = public.current_user_id()\n            AND EXISTS (\n              SELECT 1 FROM public.contacts c\n              WHERE c.user_id = decisions.actor_id\n                AND c.winger_id = public.current_user_id()\n                AND c.wingperson_status = 'ACTIVE'\n            )\n          )\n        ))",
    )
    op.drop_entity(public_decisions_decisions_insert)

    public_decisions_decisions_select = PGPolicy(
        schema="public",
        signature="decisions_select",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          actor_id = public.current_user_id()\n          OR recipient_id = public.current_user_id()\n          OR suggested_by = public.current_user_id()\n        ))",
    )
    op.drop_entity(public_decisions_decisions_select)

    public_contacts_contacts_delete = PGPolicy(
        schema="public",
        signature="contacts_delete",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.drop_entity(public_contacts_contacts_delete)

    public_contacts_contacts_update = PGPolicy(
        schema="public",
        signature="contacts_update",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id() OR winger_id = public.current_user_id()))",
    )
    op.drop_entity(public_contacts_contacts_update)

    public_contacts_contacts_insert = PGPolicy(
        schema="public",
        signature="contacts_insert",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.drop_entity(public_contacts_contacts_insert)

    public_contacts_contacts_select = PGPolicy(
        schema="public",
        signature="contacts_select",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id() OR winger_id = public.current_user_id()))",
    )
    op.drop_entity(public_contacts_contacts_select)

    public_prompt_responses_prompt_responses_update = PGPolicy(
        schema="public",
        signature="prompt_responses_update",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1\n            FROM public.profile_prompts pp\n            JOIN public.dating_profiles dp ON dp.id = pp.dating_profile_id\n            WHERE pp.id = prompt_responses.profile_prompt_id\n              AND dp.user_id = public.current_user_id()\n          )\n        ))",
    )
    op.drop_entity(public_prompt_responses_prompt_responses_update)

    public_prompt_responses_prompt_responses_insert = PGPolicy(
        schema="public",
        signature="prompt_responses_insert",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.drop_entity(public_prompt_responses_prompt_responses_insert)

    public_prompt_responses_prompt_responses_select = PGPolicy(
        schema="public",
        signature="prompt_responses_select",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          user_id = public.current_user_id()\n          OR EXISTS (\n            SELECT 1\n            FROM public.profile_prompts pp\n            JOIN public.dating_profiles dp ON dp.id = pp.dating_profile_id\n            WHERE pp.id = prompt_responses.profile_prompt_id\n              AND dp.user_id = public.current_user_id()\n          )\n        ))",
    )
    op.drop_entity(public_prompt_responses_prompt_responses_select)

    public_profile_prompts_profile_prompts_delete = PGPolicy(
        schema="public",
        signature="profile_prompts_delete",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_prompts.dating_profile_id\n              AND dp.user_id = public.current_user_id()\n          )\n        ))",
    )
    op.drop_entity(public_profile_prompts_profile_prompts_delete)

    public_profile_prompts_profile_prompts_update = PGPolicy(
        schema="public",
        signature="profile_prompts_update",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_prompts.dating_profile_id\n              AND dp.user_id = public.current_user_id()\n          )\n        ))",
    )
    op.drop_entity(public_profile_prompts_profile_prompts_update)

    public_profile_prompts_profile_prompts_insert = PGPolicy(
        schema="public",
        signature="profile_prompts_insert",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_prompts.dating_profile_id\n              AND dp.user_id = public.current_user_id()\n          )\n        ))",
    )
    op.drop_entity(public_profile_prompts_profile_prompts_insert)

    public_profile_prompts_profile_prompts_select = PGPolicy(
        schema="public",
        signature="profile_prompts_select",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_prompts.dating_profile_id\n              AND (dp.is_active = true OR dp.user_id = public.current_user_id())\n          )\n        ))",
    )
    op.drop_entity(public_profile_prompts_profile_prompts_select)

    public_profile_photos_profile_photos_delete = PGPolicy(
        schema="public",
        signature="profile_photos_delete",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_photos.dating_profile_id\n              AND dp.user_id = public.current_user_id()\n          )\n          OR profile_photos.suggester_id = public.current_user_id()\n        ))",
    )
    op.drop_entity(public_profile_photos_profile_photos_delete)

    public_profile_photos_profile_photos_update = PGPolicy(
        schema="public",
        signature="profile_photos_update",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_photos.dating_profile_id\n              AND dp.user_id = public.current_user_id()\n          )\n        ))",
    )
    op.drop_entity(public_profile_photos_profile_photos_update)

    public_profile_photos_profile_photos_insert = PGPolicy(
        schema="public",
        signature="profile_photos_insert",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_photos.dating_profile_id\n              AND (\n                dp.user_id = public.current_user_id()\n                OR (\n                  profile_photos.suggester_id = public.current_user_id()\n                  AND public.is_active_wingperson(dp.user_id)\n                )\n              )\n          )\n        ))",
    )
    op.drop_entity(public_profile_photos_profile_photos_insert)

    public_profile_photos_profile_photos_select = PGPolicy(
        schema="public",
        signature="profile_photos_select",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_photos.dating_profile_id\n              AND (\n                dp.user_id = public.current_user_id()\n                OR profile_photos.suggester_id = public.current_user_id()\n                OR (dp.is_active = true AND profile_photos.approved_at IS NOT NULL)\n              )\n          )\n        ))",
    )
    op.drop_entity(public_profile_photos_profile_photos_select)

    public_dating_profiles_dating_profiles_delete = PGPolicy(
        schema="public",
        signature="dating_profiles_delete",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.drop_entity(public_dating_profiles_dating_profiles_delete)

    public_dating_profiles_dating_profiles_update = PGPolicy(
        schema="public",
        signature="dating_profiles_update",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.drop_entity(public_dating_profiles_dating_profiles_update)

    public_dating_profiles_dating_profiles_insert = PGPolicy(
        schema="public",
        signature="dating_profiles_insert",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.drop_entity(public_dating_profiles_dating_profiles_insert)

    public_dating_profiles_dating_profiles_select = PGPolicy(
        schema="public",
        signature="dating_profiles_select",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (is_active = true OR user_id = public.current_user_id()))",
    )
    op.drop_entity(public_dating_profiles_dating_profiles_select)

    public_profiles_profiles_update = PGPolicy(
        schema="public",
        signature="profiles_update",
        on_entity="public.profiles",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (id = public.current_user_id()))",
    )
    op.drop_entity(public_profiles_profiles_update)

    public_profiles_profiles_insert = PGPolicy(
        schema="public",
        signature="profiles_insert",
        on_entity="public.profiles",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (id = public.current_user_id()))",
    )
    op.drop_entity(public_profiles_profiles_insert)

    public_is_active_wingperson = PGFunction(
        schema="public",
        signature="is_active_wingperson(_dater uuid)",
        definition="returns boolean\n        language sql\n        stable\n        security invoker\n        set search_path = public\n        as $$\n          select exists (\n            select 1 from public.contacts\n            where user_id = _dater\n              and winger_id = public.current_user_id()\n              and wingperson_status = 'ACTIVE'\n          );\n        $$",
    )
    op.drop_entity(public_is_active_wingperson)

    public_prompt_templates_prompt_templates_select = PGPolicy(
        schema="public",
        signature="prompt_templates_select",
        on_entity="public.prompt_templates",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (true)",
    )
    op.drop_entity(public_prompt_templates_prompt_templates_select)

    public_profiles_profiles_select = PGPolicy(
        schema="public",
        signature="profiles_select",
        on_entity="public.profiles",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (true)",
    )
    op.drop_entity(public_profiles_profiles_select)

    public_is_system_mode = PGFunction(
        schema="public",
        signature="is_system_mode()",
        definition="returns boolean\n        language sql\n        stable\n        as $$\n          select coalesce(nullif(current_setting('app.is_system_mode', true), '')::boolean, false)\n        $$",
    )
    op.drop_entity(public_is_system_mode)

    public_current_user_id = PGFunction(
        schema="public",
        signature="current_user_id()",
        definition="returns uuid\n        language sql\n        stable\n        as $$\n          select nullif(current_setting('app.user_id', true), '')::uuid\n        $$",
    )
    op.drop_entity(public_current_user_id)

    # ### end Alembic commands ###
