"""rls policies functions and grants

Revision ID: 41e71251b338
Revises: 4b908109b662
Create Date: 2026-06-29 03:36:23.264112+00:00

"""

from typing import Sequence

from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_policy import PGPolicy

from alembic import op
from app.platform.base.rls_grants import app_grants_sql

# revision identifiers, used by Alembic.
revision: str = "41e71251b338"
down_revision: str | None = "4b908109b662"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_is_active_wingperson = PGFunction(
        schema="public",
        signature="is_active_wingperson(_dater integer)",
        definition="returns boolean\n        language sql\n        stable\n        security invoker\n        set search_path = public\n        as $$\n          select exists (\n            select 1 from public.contacts\n            where user_id = _dater\n              and winger_id = public.current_user_id()\n              and wingperson_status = 'ACTIVE'\n          );\n        $$",
    )
    op.create_entity(public_is_active_wingperson)

    public_profiles_profiles_select = PGPolicy(
        schema="public",
        signature="profiles_select",
        on_entity="public.profiles",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (true)",
    )
    op.create_entity(public_profiles_profiles_select)

    public_profiles_profiles_insert = PGPolicy(
        schema="public",
        signature="profiles_insert",
        on_entity="public.profiles",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (id = public.current_user_id()))",
    )
    op.create_entity(public_profiles_profiles_insert)

    public_profiles_profiles_update = PGPolicy(
        schema="public",
        signature="profiles_update",
        on_entity="public.profiles",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (id = public.current_user_id()))",
    )
    op.create_entity(public_profiles_profiles_update)

    public_dating_profiles_dating_profiles_select = PGPolicy(
        schema="public",
        signature="dating_profiles_select",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (is_active = true OR user_id = public.current_user_id()))",
    )
    op.create_entity(public_dating_profiles_dating_profiles_select)

    public_dating_profiles_dating_profiles_insert = PGPolicy(
        schema="public",
        signature="dating_profiles_insert",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.create_entity(public_dating_profiles_dating_profiles_insert)

    public_dating_profiles_dating_profiles_update = PGPolicy(
        schema="public",
        signature="dating_profiles_update",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.create_entity(public_dating_profiles_dating_profiles_update)

    public_dating_profiles_dating_profiles_delete = PGPolicy(
        schema="public",
        signature="dating_profiles_delete",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.create_entity(public_dating_profiles_dating_profiles_delete)

    public_profile_photos_profile_photos_public_select = PGPolicy(
        schema="public",
        signature="profile_photos_public_select",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (\n          profile_photos.suggester_id = public.current_user_id()\n          OR EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_photos.dating_profile_id\n              AND dp.is_active = true\n              AND profile_photos.approved_at IS NOT NULL\n          )\n        )",
    )
    op.create_entity(public_profile_photos_profile_photos_public_select)

    public_prompt_templates_prompt_templates_select = PGPolicy(
        schema="public",
        signature="prompt_templates_select",
        on_entity="public.prompt_templates",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (true)",
    )
    op.create_entity(public_prompt_templates_prompt_templates_select)

    public_profile_prompts_profile_prompts_public_select = PGPolicy(
        schema="public",
        signature="profile_prompts_public_select",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_prompts.dating_profile_id\n              AND dp.is_active = true\n          )\n        )",
    )
    op.create_entity(public_profile_prompts_profile_prompts_public_select)

    public_prompt_responses_prompt_responses_select = PGPolicy(
        schema="public",
        signature="prompt_responses_select",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          user_id = public.current_user_id()\n          OR profile_owner_id = public.current_user_id()\n        ))",
    )
    op.create_entity(public_prompt_responses_prompt_responses_select)

    public_prompt_responses_prompt_responses_insert = PGPolicy(
        schema="public",
        signature="prompt_responses_insert",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.create_entity(public_prompt_responses_prompt_responses_insert)

    public_prompt_responses_prompt_responses_update = PGPolicy(
        schema="public",
        signature="prompt_responses_update",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (profile_owner_id = public.current_user_id()))",
    )
    op.create_entity(public_prompt_responses_prompt_responses_update)

    public_contacts_contacts_select = PGPolicy(
        schema="public",
        signature="contacts_select",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id() OR winger_id = public.current_user_id()))",
    )
    op.create_entity(public_contacts_contacts_select)

    public_contacts_contacts_insert = PGPolicy(
        schema="public",
        signature="contacts_insert",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.create_entity(public_contacts_contacts_insert)

    public_contacts_contacts_update = PGPolicy(
        schema="public",
        signature="contacts_update",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id() OR winger_id = public.current_user_id()))",
    )
    op.create_entity(public_contacts_contacts_update)

    public_contacts_contacts_delete = PGPolicy(
        schema="public",
        signature="contacts_delete",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.create_entity(public_contacts_contacts_delete)

    public_decisions_decisions_select = PGPolicy(
        schema="public",
        signature="decisions_select",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          actor_id = public.current_user_id()\n          OR recipient_id = public.current_user_id()\n          OR suggested_by = public.current_user_id()\n        ))",
    )
    op.create_entity(public_decisions_decisions_select)

    public_decisions_decisions_insert = PGPolicy(
        schema="public",
        signature="decisions_insert",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (\n          actor_id = public.current_user_id()\n          OR (\n            suggested_by = public.current_user_id()\n            AND EXISTS (\n              SELECT 1 FROM public.contacts c\n              WHERE c.user_id = decisions.actor_id\n                AND c.winger_id = public.current_user_id()\n                AND c.wingperson_status = 'ACTIVE'\n            )\n          )\n        ))",
    )
    op.create_entity(public_decisions_decisions_insert)

    public_decisions_decisions_update = PGPolicy(
        schema="public",
        signature="decisions_update",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (actor_id = public.current_user_id()))",
    )
    op.create_entity(public_decisions_decisions_update)

    public_matches_matches_select = PGPolicy(
        schema="public",
        signature="matches_select",
        on_entity="public.matches",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          user_a_id = public.current_user_id() OR user_b_id = public.current_user_id()\n        ))",
    )
    op.create_entity(public_matches_matches_select)

    public_matches_matches_insert = PGPolicy(
        schema="public",
        signature="matches_insert",
        on_entity="public.matches",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode())",
    )
    op.create_entity(public_matches_matches_insert)

    public_messages_messages_select = PGPolicy(
        schema="public",
        signature="messages_select",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.matches m\n            WHERE m.id = messages.match_id\n              AND (m.user_a_id = public.current_user_id() OR m.user_b_id = public.current_user_id())\n          )\n        ))",
    )
    op.create_entity(public_messages_messages_select)

    public_messages_messages_insert = PGPolicy(
        schema="public",
        signature="messages_insert",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (\n          sender_id = public.current_user_id()\n          AND EXISTS (\n            SELECT 1 FROM public.matches m\n            WHERE m.id = messages.match_id\n              AND (m.user_a_id = public.current_user_id() OR m.user_b_id = public.current_user_id())\n          )\n        ))",
    )
    op.create_entity(public_messages_messages_insert)

    public_messages_messages_update = PGPolicy(
        schema="public",
        signature="messages_update",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (sender_id = public.current_user_id()))",
    )
    op.create_entity(public_messages_messages_update)

    public_profile_reports_profile_reports_select = PGPolicy(
        schema="public",
        signature="profile_reports_select",
        on_entity="public.profile_reports",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (reporter_id = public.current_user_id()))",
    )
    op.create_entity(public_profile_reports_profile_reports_select)

    public_profile_reports_profile_reports_insert = PGPolicy(
        schema="public",
        signature="profile_reports_insert",
        on_entity="public.profile_reports",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (reporter_id = public.current_user_id()))",
    )
    op.create_entity(public_profile_reports_profile_reports_insert)

    public_magic_link_tokens_magic_link_tokens_select = PGPolicy(
        schema="public",
        signature="magic_link_tokens_select",
        on_entity="public.magic_link_tokens",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (true)",
    )
    op.create_entity(public_magic_link_tokens_magic_link_tokens_select)

    public_magic_link_tokens_magic_link_tokens_insert = PGPolicy(
        schema="public",
        signature="magic_link_tokens_insert",
        on_entity="public.magic_link_tokens",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (true)",
    )
    op.create_entity(public_magic_link_tokens_magic_link_tokens_insert)

    public_magic_link_tokens_magic_link_tokens_update = PGPolicy(
        schema="public",
        signature="magic_link_tokens_update",
        on_entity="public.magic_link_tokens",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (true)",
    )
    op.create_entity(public_magic_link_tokens_magic_link_tokens_update)

    public_profile_prompts_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR ALL\n        TO pear_app\n        USING (public.is_system_mode() OR owner_id = public.current_user_id())\n        WITH CHECK (public.is_system_mode() OR owner_id = public.current_user_id())",
    )
    op.create_entity(public_profile_prompts_user_scope_policy)

    public_media_media_select = PGPolicy(
        schema="public",
        signature="media_select",
        on_entity="public.media",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode()\n          OR owner_id = public.current_user_id()\n          OR public.is_active_wingperson(owner_id)\n          OR EXISTS (\n            SELECT 1\n            FROM public.profile_photos pp\n            JOIN public.dating_profiles dp ON dp.id = pp.dating_profile_id\n            WHERE pp.media_id = media.id\n              AND (\n                dp.user_id = public.current_user_id()\n                OR pp.suggester_id = public.current_user_id()\n                OR (dp.is_active = true AND pp.approved_at IS NOT NULL)\n              )\n          )\n          OR EXISTS (\n            SELECT 1 FROM public.profiles p WHERE p.avatar_media_id = media.id\n          ))",
    )
    op.create_entity(public_media_media_select)

    public_media_media_insert = PGPolicy(
        schema="public",
        signature="media_insert",
        on_entity="public.media",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode()\n          OR owner_id = public.current_user_id()\n          OR public.is_active_wingperson(owner_id))",
    )
    op.create_entity(public_media_media_insert)

    public_media_media_update = PGPolicy(
        schema="public",
        signature="media_update",
        on_entity="public.media",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode()\n          OR owner_id = public.current_user_id()\n          OR public.is_active_wingperson(owner_id))",
    )
    op.create_entity(public_media_media_update)

    public_media_media_delete = PGPolicy(
        schema="public",
        signature="media_delete",
        on_entity="public.media",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode()\n          OR owner_id = public.current_user_id()\n          OR public.is_active_wingperson(owner_id))",
    )
    op.create_entity(public_media_media_delete)

    public_profile_photos_wingperson_scope_policy = PGPolicy(
        schema="public",
        signature="wingperson_scope_policy",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR ALL\n        TO pear_app\n        USING (public.is_system_mode() OR owner_id = public.current_user_id() OR public.is_active_wingperson(owner_id))\n        WITH CHECK (public.is_system_mode() OR owner_id = public.current_user_id() OR public.is_active_wingperson(owner_id))",
    )
    op.create_entity(public_profile_photos_wingperson_scope_policy)

    op.enable_rls("public", "contacts")
    op.enable_rls("public", "dating_profiles")
    op.enable_rls("public", "decisions")
    op.enable_rls("public", "magic_link_tokens")
    op.enable_rls("public", "matches")
    op.enable_rls("public", "media")
    op.enable_rls("public", "messages")
    op.enable_rls("public", "profile_photos")
    op.enable_rls("public", "profile_prompts")
    op.enable_rls("public", "profile_reports")
    op.enable_rls("public", "profiles")
    op.create_foreign_key(
        "fk_profiles_avatar_media_id",
        "profiles",
        "media",
        ["avatar_media_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.enable_rls("public", "prompt_responses")
    op.enable_rls("public", "prompt_templates")
    # ### end Alembic commands ###

    # Re-assert the centralized GRANT block now that the three RLS helper functions
    # exist (pear_app needs EXECUTE on them so the policies above can call them).
    # Idempotent; guarded on role existence.
    op.execute(app_grants_sql())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.disable_rls("public", "prompt_templates")
    op.disable_rls("public", "prompt_responses")
    op.drop_constraint("fk_profiles_avatar_media_id", "profiles", type_="foreignkey")
    op.disable_rls("public", "profiles")
    op.disable_rls("public", "profile_reports")
    op.disable_rls("public", "profile_prompts")
    op.disable_rls("public", "profile_photos")
    op.disable_rls("public", "messages")
    op.disable_rls("public", "media")
    op.disable_rls("public", "matches")
    op.disable_rls("public", "magic_link_tokens")
    op.disable_rls("public", "decisions")
    op.disable_rls("public", "dating_profiles")
    op.disable_rls("public", "contacts")
    public_profile_photos_wingperson_scope_policy = PGPolicy(
        schema="public",
        signature="wingperson_scope_policy",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR ALL\n        TO pear_app\n        USING (public.is_system_mode() OR owner_id = public.current_user_id() OR public.is_active_wingperson(owner_id))\n        WITH CHECK (public.is_system_mode() OR owner_id = public.current_user_id() OR public.is_active_wingperson(owner_id))",
    )
    op.drop_entity(public_profile_photos_wingperson_scope_policy)

    public_media_media_delete = PGPolicy(
        schema="public",
        signature="media_delete",
        on_entity="public.media",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode()\n          OR owner_id = public.current_user_id()\n          OR public.is_active_wingperson(owner_id))",
    )
    op.drop_entity(public_media_media_delete)

    public_media_media_update = PGPolicy(
        schema="public",
        signature="media_update",
        on_entity="public.media",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode()\n          OR owner_id = public.current_user_id()\n          OR public.is_active_wingperson(owner_id))",
    )
    op.drop_entity(public_media_media_update)

    public_media_media_insert = PGPolicy(
        schema="public",
        signature="media_insert",
        on_entity="public.media",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode()\n          OR owner_id = public.current_user_id()\n          OR public.is_active_wingperson(owner_id))",
    )
    op.drop_entity(public_media_media_insert)

    public_media_media_select = PGPolicy(
        schema="public",
        signature="media_select",
        on_entity="public.media",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode()\n          OR owner_id = public.current_user_id()\n          OR public.is_active_wingperson(owner_id)\n          OR EXISTS (\n            SELECT 1\n            FROM public.profile_photos pp\n            JOIN public.dating_profiles dp ON dp.id = pp.dating_profile_id\n            WHERE pp.media_id = media.id\n              AND (\n                dp.user_id = public.current_user_id()\n                OR pp.suggester_id = public.current_user_id()\n                OR (dp.is_active = true AND pp.approved_at IS NOT NULL)\n              )\n          )\n          OR EXISTS (\n            SELECT 1 FROM public.profiles p WHERE p.avatar_media_id = media.id\n          ))",
    )
    op.drop_entity(public_media_media_select)

    public_profile_prompts_user_scope_policy = PGPolicy(
        schema="public",
        signature="user_scope_policy",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR ALL\n        TO pear_app\n        USING (public.is_system_mode() OR owner_id = public.current_user_id())\n        WITH CHECK (public.is_system_mode() OR owner_id = public.current_user_id())",
    )
    op.drop_entity(public_profile_prompts_user_scope_policy)

    public_magic_link_tokens_magic_link_tokens_update = PGPolicy(
        schema="public",
        signature="magic_link_tokens_update",
        on_entity="public.magic_link_tokens",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (true)",
    )
    op.drop_entity(public_magic_link_tokens_magic_link_tokens_update)

    public_magic_link_tokens_magic_link_tokens_insert = PGPolicy(
        schema="public",
        signature="magic_link_tokens_insert",
        on_entity="public.magic_link_tokens",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (true)",
    )
    op.drop_entity(public_magic_link_tokens_magic_link_tokens_insert)

    public_magic_link_tokens_magic_link_tokens_select = PGPolicy(
        schema="public",
        signature="magic_link_tokens_select",
        on_entity="public.magic_link_tokens",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (true)",
    )
    op.drop_entity(public_magic_link_tokens_magic_link_tokens_select)

    public_profile_reports_profile_reports_insert = PGPolicy(
        schema="public",
        signature="profile_reports_insert",
        on_entity="public.profile_reports",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (reporter_id = public.current_user_id()))",
    )
    op.drop_entity(public_profile_reports_profile_reports_insert)

    public_profile_reports_profile_reports_select = PGPolicy(
        schema="public",
        signature="profile_reports_select",
        on_entity="public.profile_reports",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (reporter_id = public.current_user_id()))",
    )
    op.drop_entity(public_profile_reports_profile_reports_select)

    public_messages_messages_update = PGPolicy(
        schema="public",
        signature="messages_update",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (sender_id = public.current_user_id()))",
    )
    op.drop_entity(public_messages_messages_update)

    public_messages_messages_insert = PGPolicy(
        schema="public",
        signature="messages_insert",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (\n          sender_id = public.current_user_id()\n          AND EXISTS (\n            SELECT 1 FROM public.matches m\n            WHERE m.id = messages.match_id\n              AND (m.user_a_id = public.current_user_id() OR m.user_b_id = public.current_user_id())\n          )\n        ))",
    )
    op.drop_entity(public_messages_messages_insert)

    public_messages_messages_select = PGPolicy(
        schema="public",
        signature="messages_select",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          EXISTS (\n            SELECT 1 FROM public.matches m\n            WHERE m.id = messages.match_id\n              AND (m.user_a_id = public.current_user_id() OR m.user_b_id = public.current_user_id())\n          )\n        ))",
    )
    op.drop_entity(public_messages_messages_select)

    public_matches_matches_insert = PGPolicy(
        schema="public",
        signature="matches_insert",
        on_entity="public.matches",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode())",
    )
    op.drop_entity(public_matches_matches_insert)

    public_matches_matches_select = PGPolicy(
        schema="public",
        signature="matches_select",
        on_entity="public.matches",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          user_a_id = public.current_user_id() OR user_b_id = public.current_user_id()\n        ))",
    )
    op.drop_entity(public_matches_matches_select)

    public_decisions_decisions_update = PGPolicy(
        schema="public",
        signature="decisions_update",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (actor_id = public.current_user_id()))",
    )
    op.drop_entity(public_decisions_decisions_update)

    public_decisions_decisions_insert = PGPolicy(
        schema="public",
        signature="decisions_insert",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (\n          actor_id = public.current_user_id()\n          OR (\n            suggested_by = public.current_user_id()\n            AND EXISTS (\n              SELECT 1 FROM public.contacts c\n              WHERE c.user_id = decisions.actor_id\n                AND c.winger_id = public.current_user_id()\n                AND c.wingperson_status = 'ACTIVE'\n            )\n          )\n        ))",
    )
    op.drop_entity(public_decisions_decisions_insert)

    public_decisions_decisions_select = PGPolicy(
        schema="public",
        signature="decisions_select",
        on_entity="public.decisions",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          actor_id = public.current_user_id()\n          OR recipient_id = public.current_user_id()\n          OR suggested_by = public.current_user_id()\n        ))",
    )
    op.drop_entity(public_decisions_decisions_select)

    public_contacts_contacts_delete = PGPolicy(
        schema="public",
        signature="contacts_delete",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.drop_entity(public_contacts_contacts_delete)

    public_contacts_contacts_update = PGPolicy(
        schema="public",
        signature="contacts_update",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id() OR winger_id = public.current_user_id()))",
    )
    op.drop_entity(public_contacts_contacts_update)

    public_contacts_contacts_insert = PGPolicy(
        schema="public",
        signature="contacts_insert",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.drop_entity(public_contacts_contacts_insert)

    public_contacts_contacts_select = PGPolicy(
        schema="public",
        signature="contacts_select",
        on_entity="public.contacts",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id() OR winger_id = public.current_user_id()))",
    )
    op.drop_entity(public_contacts_contacts_select)

    public_prompt_responses_prompt_responses_update = PGPolicy(
        schema="public",
        signature="prompt_responses_update",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (profile_owner_id = public.current_user_id()))",
    )
    op.drop_entity(public_prompt_responses_prompt_responses_update)

    public_prompt_responses_prompt_responses_insert = PGPolicy(
        schema="public",
        signature="prompt_responses_insert",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.drop_entity(public_prompt_responses_prompt_responses_insert)

    public_prompt_responses_prompt_responses_select = PGPolicy(
        schema="public",
        signature="prompt_responses_select",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (\n          user_id = public.current_user_id()\n          OR profile_owner_id = public.current_user_id()\n        ))",
    )
    op.drop_entity(public_prompt_responses_prompt_responses_select)

    public_profile_prompts_profile_prompts_public_select = PGPolicy(
        schema="public",
        signature="profile_prompts_public_select",
        on_entity="public.profile_prompts",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (\n          EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_prompts.dating_profile_id\n              AND dp.is_active = true\n          )\n        )",
    )
    op.drop_entity(public_profile_prompts_profile_prompts_public_select)

    public_prompt_templates_prompt_templates_select = PGPolicy(
        schema="public",
        signature="prompt_templates_select",
        on_entity="public.prompt_templates",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (true)",
    )
    op.drop_entity(public_prompt_templates_prompt_templates_select)

    public_profile_photos_profile_photos_public_select = PGPolicy(
        schema="public",
        signature="profile_photos_public_select",
        on_entity="public.profile_photos",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (\n          profile_photos.suggester_id = public.current_user_id()\n          OR EXISTS (\n            SELECT 1 FROM public.dating_profiles dp\n            WHERE dp.id = profile_photos.dating_profile_id\n              AND dp.is_active = true\n              AND profile_photos.approved_at IS NOT NULL\n          )\n        )",
    )
    op.drop_entity(public_profile_photos_profile_photos_public_select)

    public_dating_profiles_dating_profiles_delete = PGPolicy(
        schema="public",
        signature="dating_profiles_delete",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR DELETE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.drop_entity(public_dating_profiles_dating_profiles_delete)

    public_dating_profiles_dating_profiles_update = PGPolicy(
        schema="public",
        signature="dating_profiles_update",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.drop_entity(public_dating_profiles_dating_profiles_update)

    public_dating_profiles_dating_profiles_insert = PGPolicy(
        schema="public",
        signature="dating_profiles_insert",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (user_id = public.current_user_id()))",
    )
    op.drop_entity(public_dating_profiles_dating_profiles_insert)

    public_dating_profiles_dating_profiles_select = PGPolicy(
        schema="public",
        signature="dating_profiles_select",
        on_entity="public.dating_profiles",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR (is_active = true OR user_id = public.current_user_id()))",
    )
    op.drop_entity(public_dating_profiles_dating_profiles_select)

    public_profiles_profiles_update = PGPolicy(
        schema="public",
        signature="profiles_update",
        on_entity="public.profiles",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR (id = public.current_user_id()))",
    )
    op.drop_entity(public_profiles_profiles_update)

    public_profiles_profiles_insert = PGPolicy(
        schema="public",
        signature="profiles_insert",
        on_entity="public.profiles",
        definition="AS PERMISSIVE\n        FOR INSERT\n        TO pear_app\n        WITH CHECK (public.is_system_mode() OR (id = public.current_user_id()))",
    )
    op.drop_entity(public_profiles_profiles_insert)

    public_profiles_profiles_select = PGPolicy(
        schema="public",
        signature="profiles_select",
        on_entity="public.profiles",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (true)",
    )
    op.drop_entity(public_profiles_profiles_select)

    public_is_active_wingperson = PGFunction(
        schema="public",
        signature="is_active_wingperson(_dater integer)",
        definition="returns boolean\n        language sql\n        stable\n        security invoker\n        set search_path = public\n        as $$\n          select exists (\n            select 1 from public.contacts\n            where user_id = _dater\n              and winger_id = public.current_user_id()\n              and wingperson_status = 'ACTIVE'\n          );\n        $$",
    )
    op.drop_entity(public_is_active_wingperson)

    # ### end Alembic commands ###
