"""coarsen prompt_responses read to authenticated

Revision ID: e841c4a09f5b
Revises: 8cbb6402f2b9
Create Date: 2026-07-01 22:13:36.351937+00:00

"""

from typing import Sequence

from alembic_utils.pg_policy import PGPolicy

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e841c4a09f5b"
down_revision: str | None = "8cbb6402f2b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_prompt_responses_prompt_responses_select = PGPolicy(
        schema="public",
        signature="prompt_responses_select",
        on_entity="public.prompt_responses",
        definition="AS PERMISSIVE\n        FOR SELECT\n        TO pear_app\n        USING (public.is_system_mode() OR public.current_user_id() IS NOT NULL)",
    )
    op.replace_entity(public_prompt_responses_prompt_responses_select)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_prompt_responses_prompt_responses_select = PGPolicy(
        schema="public",
        signature="prompt_responses_select",
        on_entity="public.prompt_responses",
        definition="as PERMISSIVE for SELECT to pear_app using (is_system_mode() OR ((user_id = current_user_id()) OR (profile_owner_id = current_user_id())))",
    )
    op.replace_entity(public_prompt_responses_prompt_responses_select)
    # ### end Alembic commands ###
