"""initial schema (int+sqid)

Revision ID: 4b908109b662
Revises:
Create Date: 2026-06-29 03:36:09.176780+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy.dialects import postgresql

from alembic import op
from app.config import config as app_config
from app.domain.contacts.enums import WingpersonStatus
from app.domain.dating_profiles.enums import City, DatingStatus, Interest, Religion
from app.domain.decisions.enums import DecisionType
from app.domain.profiles.enums import Gender, UserRole
from app.platform.auth.enums import AuthProvider
from app.platform.base.rls_grants import app_grants_sql, app_role_bootstrap_sql
from app.platform.comms.enums import MessageDirection, MessageState
from app.platform.events.enums import EventType
from app.platform.media.enums import MediaState
from app.platform.queue.enums import TaskStatus
from app.utils.sqids import SqidType
from app.utils.textenum import TextEnum

# revision identifiers, used by Alembic.
revision: str = "4b908109b662"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_current_user_id = PGFunction(
        schema="public",
        signature="current_user_id()",
        definition="returns integer\n        language sql\n        stable\n        as $$\n          select nullif(current_setting('app.user_id', true), '')::integer\n        $$",
    )
    op.create_entity(public_current_user_id)

    public_is_system_mode = PGFunction(
        schema="public",
        signature="is_system_mode()",
        definition="returns boolean\n        language sql\n        stable\n        as $$\n          select coalesce(nullif(current_setting('app.is_system_mode', true), '')::boolean, false)\n        $$",
    )
    op.create_entity(public_is_system_mode)

    op.create_table(
        "email_messages",
        sa.Column("user_id", SqidType(), nullable=True),
        sa.Column("direction", TextEnum(MessageDirection), nullable=False),
        sa.Column("state", TextEnum(MessageState), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("from_email", sa.Text(), nullable=True),
        sa.Column("from_name", sa.Text(), nullable=True),
        sa.Column("to_emails", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("reply_to_email", sa.Text(), nullable=True),
        sa.Column("template_name", sa.Text(), nullable=True),
        sa.Column("ses_message_id", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_messages_deleted_at"), "email_messages", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_email_messages_ses_message_id"), "email_messages", ["ses_message_id"], unique=True)
    op.create_index(op.f("ix_email_messages_user_id"), "email_messages", ["user_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("actor_id", SqidType(), nullable=True),
        sa.Column("object_type", sa.String(length=50), nullable=False),
        sa.Column("object_id", SqidType(), nullable=False),
        sa.Column("event_type", TextEnum(EventType), nullable=False),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_actor_id"), "events", ["actor_id"], unique=False)
    op.create_index(op.f("ix_events_deleted_at"), "events", ["deleted_at"], unique=False)
    op.create_index("ix_events_object", "events", ["object_type", "object_id", "created_at"], unique=False)
    op.create_table(
        "magic_link_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_magic_link_tokens_deleted_at"), "magic_link_tokens", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_magic_link_tokens_token_hash"), "magic_link_tokens", ["token_hash"], unique=True)
    op.create_table(
        "profiles",
        sa.Column("chosen_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("phone_number", sa.Text(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", TextEnum(Gender), nullable=True),
        sa.Column("role", TextEnum(UserRole), server_default="DATER", nullable=False),
        sa.Column("avatar_media_id", SqidType(), nullable=True),
        sa.Column("push_token", sa.Text(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["avatar_media_id"], ["media.id"], name="fk_profiles_avatar_media_id", ondelete="SET NULL", use_alter=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_deleted_at"), "profiles", ["deleted_at"], unique=False)
    op.create_table(
        "prompt_templates",
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompt_templates_deleted_at"), "prompt_templates", ["deleted_at"], unique=False)
    op.create_table(
        "state_transition_logs",
        sa.Column("object_type", sa.String(), nullable=False),
        sa.Column("object_id", SqidType(), nullable=False),
        sa.Column("from_state", sa.String(), nullable=False),
        sa.Column("to_state", sa.String(), nullable=False),
        sa.Column("actor_id", SqidType(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_state_transition_logs_deleted_at"), "state_transition_logs", ["deleted_at"], unique=False)
    op.create_index("ix_stl_object_lookup", "state_transition_logs", ["object_type", "object_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("job_key", sa.Text(), nullable=False),
        sa.Column("queue", sa.Text(), nullable=False),
        sa.Column("task_name", sa.Text(), nullable=False),
        sa.Column("status", TextEnum(TaskStatus), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_deleted_at"), "tasks", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_tasks_job_key"), "tasks", ["job_key"], unique=True)
    op.create_index(op.f("ix_tasks_task_name"), "tasks", ["task_name"], unique=False)
    op.create_table(
        "auth_identities",
        sa.Column("provider", TextEnum(AuthProvider), nullable=False),
        sa.Column("provider_subject", sa.Text(), nullable=False),
        sa.Column("profile_id", SqidType(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_subject", name="uq_auth_identity_provider_subject"),
    )
    op.create_index(op.f("ix_auth_identities_deleted_at"), "auth_identities", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_auth_identities_profile_id"), "auth_identities", ["profile_id"], unique=False)
    op.create_table(
        "contacts",
        sa.Column("user_id", SqidType(), nullable=False),
        sa.Column("phone_number", sa.Text(), nullable=False),
        sa.Column("winger_id", SqidType(), nullable=True),
        sa.Column("wingperson_status", TextEnum(WingpersonStatus), server_default="INVITED", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["winger_id"], ["profiles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contacts_deleted_at"), "contacts", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_contacts_user_id"), "contacts", ["user_id"], unique=False)
    op.create_index(op.f("ix_contacts_winger_id"), "contacts", ["winger_id"], unique=False)
    op.create_table(
        "dating_profiles",
        sa.Column("user_id", SqidType(), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("interested_gender", postgresql.ARRAY(TextEnum(Gender)), server_default="{}", nullable=False),
        sa.Column("age_from", sa.Integer(), nullable=False),
        sa.Column("age_to", sa.Integer(), nullable=True),
        sa.Column("religion", TextEnum(Religion), nullable=False),
        sa.Column("religious_preference", TextEnum(Religion), nullable=True),
        sa.Column("interests", postgresql.ARRAY(TextEnum(Interest)), server_default="{}", nullable=False),
        sa.Column("city", TextEnum(City), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("dating_status", TextEnum(DatingStatus), server_default="OPEN", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dating_profiles_deleted_at"), "dating_profiles", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_dating_profiles_user_id"), "dating_profiles", ["user_id"], unique=True)
    op.create_table(
        "decisions",
        sa.Column("actor_id", SqidType(), nullable=False),
        sa.Column("recipient_id", SqidType(), nullable=False),
        sa.Column("decision", TextEnum(DecisionType), nullable=True),
        sa.Column("suggested_by", SqidType(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("actor_id <> recipient_id", name="no_self_decision"),
        sa.ForeignKeyConstraint(["actor_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipient_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["suggested_by"], ["profiles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("actor_id", "recipient_id", name="unique_actor_recipient"),
    )
    op.create_index(op.f("ix_decisions_actor_id"), "decisions", ["actor_id"], unique=False)
    op.create_index(op.f("ix_decisions_deleted_at"), "decisions", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_decisions_recipient_id"), "decisions", ["recipient_id"], unique=False)
    op.create_index(op.f("ix_decisions_suggested_by"), "decisions", ["suggested_by"], unique=False)
    op.create_table(
        "matches",
        sa.Column("user_a_id", SqidType(), nullable=False),
        sa.Column("user_b_id", SqidType(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("user_a_id < user_b_id", name="ordered_match_ids"),
        sa.ForeignKeyConstraint(["user_a_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_b_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_a_id", "user_b_id", name="unique_match"),
    )
    op.create_index(op.f("ix_matches_deleted_at"), "matches", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_matches_user_a_id"), "matches", ["user_a_id"], unique=False)
    op.create_index(op.f("ix_matches_user_b_id"), "matches", ["user_b_id"], unique=False)
    op.create_table(
        "media",
        sa.Column("owner_id", SqidType(), nullable=False),
        sa.Column("file_key", sa.Text(), nullable=False),
        sa.Column("processed_key", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("state", TextEnum(MediaState), server_default="PENDING", nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_deleted_at"), "media", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_media_owner_id"), "media", ["owner_id"], unique=False)
    op.create_index(op.f("ix_media_state"), "media", ["state"], unique=False)
    op.create_table(
        "profile_reports",
        sa.Column("reporter_id", SqidType(), nullable=False),
        sa.Column("reported_id", SqidType(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["reported_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reporter_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profile_reports_deleted_at"), "profile_reports", ["deleted_at"], unique=False)
    op.create_table(
        "messages",
        sa.Column("match_id", SqidType(), nullable=False),
        sa.Column("sender_id", SqidType(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_deleted_at"), "messages", ["deleted_at"], unique=False)
    op.create_index("ix_messages_match_id_created_at", "messages", ["match_id", "created_at"], unique=False)
    op.create_index(op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False)
    op.create_table(
        "profile_photos",
        sa.Column("dating_profile_id", SqidType(), nullable=False),
        sa.Column("owner_id", SqidType(), nullable=False),
        sa.Column("suggester_id", SqidType(), nullable=True),
        sa.Column("media_id", SqidType(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dating_profile_id"], ["dating_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["suggester_id"], ["profiles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_profile_photos_dating_profile_id_display_order",
        "profile_photos",
        ["dating_profile_id", "display_order"],
        unique=False,
    )
    op.create_index(op.f("ix_profile_photos_deleted_at"), "profile_photos", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_profile_photos_owner_id"), "profile_photos", ["owner_id"], unique=False)
    op.create_index(
        "ix_profile_photos_suggester_id",
        "profile_photos",
        ["suggester_id"],
        unique=False,
        postgresql_where=sa.text("suggester_id IS NOT NULL"),
    )
    op.create_table(
        "profile_prompts",
        sa.Column("dating_profile_id", SqidType(), nullable=False),
        sa.Column("owner_id", SqidType(), nullable=False),
        sa.Column("prompt_template_id", SqidType(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["dating_profile_id"], ["dating_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["prompt_template_id"],
            ["prompt_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profile_prompts_deleted_at"), "profile_prompts", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_profile_prompts_owner_id"), "profile_prompts", ["owner_id"], unique=False)
    op.create_table(
        "prompt_responses",
        sa.Column("user_id", SqidType(), nullable=False),
        sa.Column("profile_owner_id", SqidType(), nullable=False),
        sa.Column("profile_prompt_id", SqidType(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_rejected", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["profile_owner_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_prompt_id"], ["profile_prompts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompt_responses_deleted_at"), "prompt_responses", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_prompt_responses_profile_owner_id"), "prompt_responses", ["profile_owner_id"], unique=False
    )
    # ### end Alembic commands ###

    # ── pear_app role bootstrap + GRANTs (privilege floor for RLS) ───────────
    # The app connects as the NON-superuser `pear_app` role under FORCE RLS, so it
    # owns nothing and grants are the privilege ceiling RLS filters against. Roles
    # are cluster-global, so create it first (idempotent; password from
    # DB_APP_PASSWORD), then grant schema USAGE, table CRUD, sequence USAGE/SELECT,
    # function EXECUTE, plus ALTER DEFAULT PRIVILEGES so later-migration objects
    # inherit the same grants. Re-asserted in the RLS migration after the helper
    # functions exist.
    op.execute(app_role_bootstrap_sql(app_config.DB_APP_PASSWORD))
    op.execute(app_grants_sql())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompt_responses_profile_owner_id"), table_name="prompt_responses")
    op.drop_index(op.f("ix_prompt_responses_deleted_at"), table_name="prompt_responses")
    op.drop_table("prompt_responses")
    op.drop_index(op.f("ix_profile_prompts_owner_id"), table_name="profile_prompts")
    op.drop_index(op.f("ix_profile_prompts_deleted_at"), table_name="profile_prompts")
    op.drop_table("profile_prompts")
    op.drop_index(
        "ix_profile_photos_suggester_id",
        table_name="profile_photos",
        postgresql_where=sa.text("suggester_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_profile_photos_owner_id"), table_name="profile_photos")
    op.drop_index(op.f("ix_profile_photos_deleted_at"), table_name="profile_photos")
    op.drop_index("ix_profile_photos_dating_profile_id_display_order", table_name="profile_photos")
    op.drop_table("profile_photos")
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index("ix_messages_match_id_created_at", table_name="messages")
    op.drop_index(op.f("ix_messages_deleted_at"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_profile_reports_deleted_at"), table_name="profile_reports")
    op.drop_table("profile_reports")
    op.drop_index(op.f("ix_media_state"), table_name="media")
    op.drop_index(op.f("ix_media_owner_id"), table_name="media")
    op.drop_index(op.f("ix_media_deleted_at"), table_name="media")
    op.drop_table("media")
    op.drop_index(op.f("ix_matches_user_b_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_user_a_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_deleted_at"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_decisions_suggested_by"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_recipient_id"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_deleted_at"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_actor_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_dating_profiles_user_id"), table_name="dating_profiles")
    op.drop_index(op.f("ix_dating_profiles_deleted_at"), table_name="dating_profiles")
    op.drop_table("dating_profiles")
    op.drop_index(op.f("ix_contacts_winger_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_user_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_deleted_at"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_auth_identities_profile_id"), table_name="auth_identities")
    op.drop_index(op.f("ix_auth_identities_deleted_at"), table_name="auth_identities")
    op.drop_table("auth_identities")
    op.drop_index(op.f("ix_tasks_task_name"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_job_key"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_deleted_at"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_stl_object_lookup", table_name="state_transition_logs")
    op.drop_index(op.f("ix_state_transition_logs_deleted_at"), table_name="state_transition_logs")
    op.drop_table("state_transition_logs")
    op.drop_index(op.f("ix_prompt_templates_deleted_at"), table_name="prompt_templates")
    op.drop_table("prompt_templates")
    op.drop_index(op.f("ix_profiles_deleted_at"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_magic_link_tokens_token_hash"), table_name="magic_link_tokens")
    op.drop_index(op.f("ix_magic_link_tokens_deleted_at"), table_name="magic_link_tokens")
    op.drop_table("magic_link_tokens")
    op.drop_index("ix_events_object", table_name="events")
    op.drop_index(op.f("ix_events_deleted_at"), table_name="events")
    op.drop_index(op.f("ix_events_actor_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_email_messages_user_id"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_ses_message_id"), table_name="email_messages")
    op.drop_index(op.f("ix_email_messages_deleted_at"), table_name="email_messages")
    op.drop_table("email_messages")
    public_is_system_mode = PGFunction(
        schema="public",
        signature="is_system_mode()",
        definition="returns boolean\n        language sql\n        stable\n        as $$\n          select coalesce(nullif(current_setting('app.is_system_mode', true), '')::boolean, false)\n        $$",
    )
    op.drop_entity(public_is_system_mode)

    public_current_user_id = PGFunction(
        schema="public",
        signature="current_user_id()",
        definition="returns integer\n        language sql\n        stable\n        as $$\n          select nullif(current_setting('app.user_id', true), '')::integer\n        $$",
    )
    op.drop_entity(public_current_user_id)

    # ### end Alembic commands ###
