"""drop RLS on profiles identity table

Revision ID: e74b9f4587a7
Revises: 57d4ba2fa704
Create Date: 2026-06-29 14:57:42.612158+00:00

"""

from typing import Sequence

from alembic_utils.pg_policy import PGPolicy

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e74b9f4587a7"
down_revision: str | None = "57d4ba2fa704"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_profiles_profiles_update = PGPolicy(
        schema="public",
        signature="profiles_update",
        on_entity="public.profiles",
        definition="as PERMISSIVE for UPDATE to pear_app using (is_system_mode() OR (id = current_user_id()))",
    )
    op.drop_entity(public_profiles_profiles_update)

    public_profiles_profiles_insert = PGPolicy(
        schema="public",
        signature="profiles_insert",
        on_entity="public.profiles",
        definition="as PERMISSIVE for INSERT to pear_app with check (is_system_mode() OR (id = current_user_id()))",
    )
    op.drop_entity(public_profiles_profiles_insert)

    public_profiles_profiles_select = PGPolicy(
        schema="public",
        signature="profiles_select",
        on_entity="public.profiles",
        definition="as PERMISSIVE for SELECT to pear_app using (true)",
    )
    op.drop_entity(public_profiles_profiles_select)

    op.disable_rls("public", "profiles")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.enable_rls("public", "profiles")
    public_profiles_profiles_select = PGPolicy(
        schema="public",
        signature="profiles_select",
        on_entity="public.profiles",
        definition="as PERMISSIVE for SELECT to pear_app using (true)",
    )
    op.create_entity(public_profiles_profiles_select)

    public_profiles_profiles_insert = PGPolicy(
        schema="public",
        signature="profiles_insert",
        on_entity="public.profiles",
        definition="as PERMISSIVE for INSERT to pear_app with check (is_system_mode() OR (id = current_user_id()))",
    )
    op.create_entity(public_profiles_profiles_insert)

    public_profiles_profiles_update = PGPolicy(
        schema="public",
        signature="profiles_update",
        on_entity="public.profiles",
        definition="as PERMISSIVE for UPDATE to pear_app using (is_system_mode() OR (id = current_user_id()))",
    )
    op.create_entity(public_profiles_profiles_update)

    # ### end Alembic commands ###
