"""add wingperson invite tokens table

Revision ID: 4c8120f7b0b7
Revises: a774a0162de1
Create Date: 2026-07-10 20:55:44.954450+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op
from app.utils.sqids import SqidType

# revision identifiers, used by Alembic.
revision: str = "4c8120f7b0b7"
down_revision: str | None = "a774a0162de1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wingperson_invite_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("contact_id", SqidType(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wingperson_invite_tokens_contact_id"), "wingperson_invite_tokens", ["contact_id"], unique=False
    )
    op.create_index(
        op.f("ix_wingperson_invite_tokens_deleted_at"), "wingperson_invite_tokens", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_wingperson_invite_tokens_token_hash"), "wingperson_invite_tokens", ["token_hash"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wingperson_invite_tokens_token_hash"), table_name="wingperson_invite_tokens")
    op.drop_index(op.f("ix_wingperson_invite_tokens_deleted_at"), table_name="wingperson_invite_tokens")
    op.drop_index(op.f("ix_wingperson_invite_tokens_contact_id"), table_name="wingperson_invite_tokens")
    op.drop_table("wingperson_invite_tokens")
    # ### end Alembic commands ###
