"""auth identities and refresh tokens

Revision ID: e215e819cb18
Revises: 89a26f2a9010
Create Date: 2026-06-13 20:55:07.340240+00:00

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op
from app.platform.auth.enums import AuthProvider
from app.utils.textenum import TextEnum

# revision identifiers, used by Alembic.
revision: str = "e215e819cb18"
down_revision: str | None = "89a26f2a9010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_identities",
        sa.Column("provider", TextEnum(AuthProvider), nullable=False),
        sa.Column("provider_subject", sa.Text(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_subject", name="uq_auth_identity_provider_subject"),
    )
    op.create_index(op.f("ix_auth_identities_deleted_at"), "auth_identities", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_auth_identities_profile_id"), "auth_identities", ["profile_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("replaced_by", sa.Uuid(), nullable=True),
        sa.Column("device_info", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_deleted_at"), "refresh_tokens", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_profile_id"), "refresh_tokens", ["profile_id"], unique=False)
    op.create_index(op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_profile_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_deleted_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_auth_identities_profile_id"), table_name="auth_identities")
    op.drop_index(op.f("ix_auth_identities_deleted_at"), table_name="auth_identities")
    op.drop_table("auth_identities")
    # ### end Alembic commands ###
