"""drop native_build_fingerprints table

Revision ID: f41d2e8068fa
Revises: e841c4a09f5b
Create Date: 2026-07-09 14:25:05.683556+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f41d2e8068fa"
down_revision: str | None = "e841c4a09f5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (Autogenerate also proposed dropping ix_app_updates_update_uuid in favor of a
    # plain unique constraint on app_updates — unrelated pre-existing model/DB
    # drift, not caused by this change. Left out of this migration; not this
    # commit's concern.)
    op.drop_index(op.f("ix_native_build_fingerprints_deleted_at"), table_name="native_build_fingerprints")
    op.drop_table("native_build_fingerprints")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "native_build_fingerprints",
        sa.Column("platform", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("fingerprint", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("native_build_fingerprints_pkey")),
        sa.UniqueConstraint(
            "platform",
            name=op.f("native_build_fingerprints_platform_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_native_build_fingerprints_deleted_at"), "native_build_fingerprints", ["deleted_at"], unique=False
    )
    # ### end Alembic commands ###
