"""messages (match_id, created_at) index

Revision ID: 4cb603ce8f63
Revises: e5f6a7b8c9d0
Create Date: 2026-06-14 23:28:33.570081+00:00

"""

from typing import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cb603ce8f63"
down_revision: str | None = "e5f6a7b8c9d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_match_id"), table_name="messages")
    op.create_index("ix_messages_match_id_created_at", "messages", ["match_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_match_id_created_at", table_name="messages")
    op.create_index(op.f("ix_messages_match_id"), "messages", ["match_id"], unique=False)
    # ### end Alembic commands ###
