"""messages update RLS: match-participant, not sender-owned

Revision ID: c674b8890889
Revises: d926750af59e
Create Date: 2026-06-30 21:42:02.022318+00:00

"""

from typing import Sequence

from alembic_utils.pg_policy import PGPolicy

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c674b8890889"
down_revision: str | None = "d926750af59e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_messages_messages_update = PGPolicy(
        schema="public",
        signature="messages_update",
        on_entity="public.messages",
        definition="AS PERMISSIVE\n        FOR UPDATE\n        TO pear_app\n        USING (public.is_system_mode() OR EXISTS (SELECT 1 FROM public.matches m WHERE m.id = messages.match_id AND public.current_user_id() IN (m.user_a_id, m.user_b_id)))\n        WITH CHECK (public.is_system_mode() OR EXISTS (SELECT 1 FROM public.matches m WHERE m.id = messages.match_id AND public.current_user_id() IN (m.user_a_id, m.user_b_id)))",
    )
    op.replace_entity(public_messages_messages_update)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_messages_messages_update = PGPolicy(
        schema="public",
        signature="messages_update",
        on_entity="public.messages",
        definition="as PERMISSIVE for UPDATE to pear_app using (is_system_mode() OR (sender_id = current_user_id())) with check (is_system_mode() OR (sender_id = current_user_id()))",
    )
    op.replace_entity(public_messages_messages_update)
    # ### end Alembic commands ###
