"""add app_updates table (self-hosted OTA manifest)

Revision ID: dccdc4d3bb22
Revises: c674b8890889
Create Date: 2026-07-01 12:00:00.000000+00:00

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.platform.updates.enums import RolloutStatus, UpdateChannel, UpdatePlatform
from app.utils.sqids import SqidType
from app.utils.textenum import TextEnum

# revision identifiers, used by Alembic.
revision: str = "dccdc4d3bb22"
down_revision: str | None = "c674b8890889"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_updates",
        sa.Column(
            "update_uuid",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("runtime_version", sa.Text(), nullable=False),
        sa.Column("channel", TextEnum(UpdateChannel), nullable=False),
        sa.Column("platform", TextEnum(UpdatePlatform), nullable=False),
        sa.Column("launch_asset", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rollout", TextEnum(RolloutStatus), server_default="LIVE", nullable=False),
        sa.Column("rollout_pct", sa.Integer(), nullable=True),
        sa.Column("id", SqidType(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_app_updates_channel"), "app_updates", ["channel"], unique=False)
    op.create_index(op.f("ix_app_updates_deleted_at"), "app_updates", ["deleted_at"], unique=False)
    op.create_index(
        "ix_app_updates_lookup",
        "app_updates",
        ["runtime_version", "channel", "platform", "rollout", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_app_updates_platform"), "app_updates", ["platform"], unique=False)
    op.create_index(op.f("ix_app_updates_rollout"), "app_updates", ["rollout"], unique=False)
    op.create_index(op.f("ix_app_updates_runtime_version"), "app_updates", ["runtime_version"], unique=False)
    op.create_index(op.f("ix_app_updates_update_uuid"), "app_updates", ["update_uuid"], unique=True)

    # No RLS on this table — same call as `profiles` (see
    # `20260629_1457_drop_rls_on_profiles_identity_table_e74b9f4587a7`): both
    # `/updates/manifest` and `/updates/publish` are unauthenticated, root-mounted
    # routes with no per-request actor to scope a policy against. `pear_app`'s
    # blanket table grant (`rls_grants.py`) already covers CRUD; the bearer-token
    # guard on `/updates/publish` (`requires_updates_publish_token`) is the actual
    # floor, not RLS.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_app_updates_update_uuid"), table_name="app_updates")
    op.drop_index(op.f("ix_app_updates_runtime_version"), table_name="app_updates")
    op.drop_index(op.f("ix_app_updates_rollout"), table_name="app_updates")
    op.drop_index(op.f("ix_app_updates_platform"), table_name="app_updates")
    op.drop_index("ix_app_updates_lookup", table_name="app_updates")
    op.drop_index(op.f("ix_app_updates_deleted_at"), table_name="app_updates")
    op.drop_index(op.f("ix_app_updates_channel"), table_name="app_updates")
    op.drop_table("app_updates")
    # ### end Alembic commands ###
